### ISSUE TITLE
Script runs OK but Excel Report file not there

### ISSUE THREAD

**Issue by sesmailjee** [microsoft/ARI#101]
Ran the script from Cloudshell, it ran, 
reported Excel file saved at: /home/seif/AzureResourceInventory/AzureResourceInventory_Report_2023-01-26_17_53.xlsx
The AzureResourceInventory directory is there but no Excel Report file in it!

**Comment by Claudio-Merola** [comment]
Hello,

I believe the Import-Excel module was not installed correctly.

Can you try to install it manually?

Install-Module -Name ImportExcel -Force

**Comment by rafamaximo2022** [comment]
Estou com mesmo problema porém no powershell. Na saída mostra até a quantidade de recursos bem como o nome do arquivo que foi gerado. Porem quando vou em c:\ AzureresourceInventory o arquivo xlxs não está la. Já rodei o comentado de Install-Module mas nada. Mais alguma dica?

**Comment by rafamaximo2022** [comment]
Outra observação, precisa rodar no Powershell 7?

**Comment by nformer** [comment]
Any update on this, no reply from @sesmailjee, but I am seeing the same behavior when running on Windows desktop and Cloudshell.  

I manually ran Import-Excel by hand with force:

`Install-Module -Name ImportExcel -Force`

![image](https://user-images.githubusercontent.com/17071923/217121771-ce71755a-80dc-4694-837e-a1bb74935c61.png)

**Comment by RonaldMem** [comment]
Make sure to add the -Online parameter to the command to create the excel/xml files.

**Comment by Claudio-Merola** [comment]
The -Online parameter is not really necessary, it's just for the script to read the extra ps1 files directly from github. 

My suggestion is always to add the -Debug parameter as it gives more details if something is missing or what went wrong.

**Comment by PeterBursky** [comment]
> Hello,
> 
> I believe the Import-Excel module was not installed correctly.
> 
> Can you try to install it manually?
> 
> Install-Module -Name ImportExcel -Force

I can confirm that the solution to my missing Excel file issue was resolved once the Import-Excel module was installed correctly. In my case, this was probably made worse by OneDrive messing up the user's PowerShell folder by creating additional copies, and the installed module didn't stick.

**Comment by felipeschulz** [comment]
Hi Folks,
Try install Import-Excel module 

On your terminal, use this command:
`Install-Module -Name ImportExcel`

If you already installed this module, force update him, with:

`Update-Module -Name ImportExcel -Force`

After this, re-run Azure Resouce Inventory command
