### ISSUE TITLE
Subscription names are not populating with the -SecurtyCenter switch

### ISSUE THREAD

**Issue by ppollice** [microsoft/ARI#104]
On the sec center tab, all seems to populate properly, except the subscription field which doesn't show anything but blanks even when looking at the filtering. 

Been trying to hunt it down, but seems to see the field as null from the args.

**Comment by Patsy-P** [comment]
Disregard. Was running in VS code terminal and fixed it with 

If ($Task -eq 'Processing')
{
    $obj = ''
    $tmp = @()

    foreach ($S in $Security) {
        $data = $s.PROPERTIES

        $sub1 = $Subscriptions | Where-Object { $_.id -eq $s.properties.resourceDetails.Id.Split("/")[2] }

        $obj = @{
            'Subscription'       = $sub1.Name;
            'Resource Group'     = $S.RESOURCEGROUP;
            'Resource Type'      = $data.resourceDetails.Id.Split("/")[7];
            'Resource Name'      = $data.resourceDetails.Id.Split("/")[8];
            'Categories'         = [string]$data.metadata.categories;
            'Control'            = $data.displayName;
            'Severity'           = $data.metadata.severity;
            'Status'             = $data.status.code;
            'Remediation'        = $data.metadata.remediationDescription;
            'Remediation Effort' = $data.metadata.implementationEffort;
            'User Impact'        = $data.metadata.userImpact;
            'Threats'            = [string]$data.metadata.threats
        }    
        $tmp += $obj
    }
    $tmp
