### ISSUE TITLE
Feature request: Export to Azure Pricing

### ISSUE THREAD

**Issue by vicperdana** [microsoft/ARI#105]
It would be great if we could use data that's exported to Excel and feed into Azure Pricing calculator or provide estimate of resources cost using Azure API, such as: https://learn.microsoft.com/en-us/rest/api/cost-management/retail-prices/azure-retail-prices

**Comment by Claudio-Merola** [comment]
I've tried to add this feature (Azure Cost data) into the excel. But back then the idea was to give the real daily cost of each resource. But at least the way I was trying it was taking too much time to build the report and some resources did not have the cost information, like databricks VMs that are created and deleted multiple times during the day.

So we ended up giving up on that idea. 

But consulting the API and giving a generic cost might work.
