### ISSUE TITLE
No resources found

### ISSUE THREAD

**Issue by dmonkcbts** [microsoft/ARI#106]
I have tried running the script with different flags, but on this one tenant, it does not find anything. When I log in to the Azure portal, I see the one expected subscription and all the resources. Is there some Azure setting preventing me from running this script? Never encountered this before. The output shows 1 resource, which I think is the subscription, but nothing is in the Excel.

.\AzureResourceInventory.ps1 -tenantID xxxxxxxxx -SecurityCenter
Validating Az Cli..
Validating Az Cli Extension..
Validating ImportExcel Module..
PowerShell Desktop Identified.

Azure Cloud Environment: AzureCloud
 Azure Resource Inventory are collecting Security Center Advisories.
 Collecting Security Center Can increase considerably the execution time of Azure Resource Inventory and the size of final report

Report Complete. Total Runtime was: .93 Minutes
Total Resources: 1
Total Advisories: 115
Total Security Advisories: 0

Excel file saved at:

**Comment by Claudio-Merola** [comment]
Hello,

This is very strange. Running the inventory for other environments is ok?

The types of resources in the tenant are like VMs and AKS and etc?

**Comment by dmonkcbts** [comment]
Yes to both. Debug isn’t helpful. Doesn’t show any issues, just says it found one resource, which I assume is the subscription.

David Monk
Cloud Architect – Cloud Transformation

**Comment by dmonkcbts** [comment]
I set $Limit = 0, and I don’t see any errors. It found resources.

"total_records": 559

David Monk
Cloud Architect – Cloud Transformation

**Comment by Claudio-Merola** [comment]
Ok, 

The only parameters you are using when running the script are: -tenantID and -SecurityCenter?

What version of az cli and resource-graph extension are you running?

**Comment by dmonkcbts** [comment]
Yes, those are the only parameters.

az version
{
  "azure-cli": "2.46.0",
  "azure-cli-core": "2.46.0",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "account": "0.2.3",
    "resource-graph": "2.1.0"
  }
}

David Monk
Cloud Architect – Cloud Transformation

**Comment by Claudio-Merola** [comment]
I just tested with the exact same version and it runs normally.

Let's see what is this one resource it is reporting...

Can you see what is inside the variable $Resources after the script is run?

Thanks

**Comment by dmonkcbts** [comment]
$Resources is empty after running the script.

David Monk
Cloud Architect – Cloud Transformation

**Comment by Claudio-Merola** [comment]
May you run the following to see the types of resources being collected?


az login -t TENANTID

$Global:Resources = @()
$GraphQuery = "resources | where strlen(properties.definition.actions) < 123000 | summarize count()"
$EnvSize = az graph query -q  $GraphQuery --output json --only-show-errors | ConvertFrom-Json
$EnvSizeNum = $EnvSize.data.'count_'

Write-Host ('Resources counted: '+$EnvSizeNum)

if ($EnvSizeNum -ge 1) {
    $Loop = $EnvSizeNum / 1000
    $Loop = [math]::ceiling($Loop)
    $Looper = 0
    $Limit = 0

    while ($Looper -lt $Loop) {
        $GraphQuery = "resources | where strlen(properties.definition.actions) < 123000 | project id,name,type,tenantId,kind,location,resourceGroup,subscriptionId,managedBy,sku,plan,properties,identity,zones,extendedLocation$($GraphQueryTags) | order by id asc"
        
        $Resource = (az graph query -q $GraphQuery --skip $Limit --first 1000 --output json --only-show-errors).tolower() | ConvertFrom-Json

        write-host ('Resources Inside Loop: '+$Resource.data.count)

        $Global:Resources += $Resource.data
        Start-Sleep 2
        $Looper ++
        $Limit = $Limit + 1000
    }
}

$Resources | Group-Object -Property type | Select-Object -Property Name,Count | Sort-Object -Property count -Descending

**Comment by dmonkcbts** [comment]
Looks like the issue is found.

***@***.***

Here is a list of all the resource types they have in their subscription:

App Service plan
Runbook
API Connection
Virtual machine
SQL virtual machine
Disk
Load balancer
Network Interface
Storage account
Log Analytics workspace
SQL server
SQL database
Public IP address
Network security group
Service Bus Namespace
Virtual network
Bastion
Network Watcher
Logic app
Logic App (Standard)
Application Insights
Integration account
App Service
Azure Database for MySQL flexible server
Private DNS zone
Synapse workspace
Automation Account
Dedicated SQL pool
Key vault
Analysis Services
Azure DevOps organization


David Monk
Cloud Architect – Cloud Transformation

**Comment by dmonkcbts** [comment]
Is there something else I can do to help identify what is causing the issue with this one tenant?

David Monk
Cloud Architect – Cloud Transformation

From: Monk, David
Sent: Friday, March 31, 2023 8:34 AM
To: 'microsoft/ARI' ***@***.***>; microsoft/ARI ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [microsoft/ARI] No resources found (Issue #106)

Looks like the issue is found.

***@***.***

Here is a list of all the resource types they have in their subscription:

App Service plan
Runbook
API Connection
Virtual machine
SQL virtual machine
Disk
Load balancer
Network Interface
Storage account
Log Analytics workspace
SQL server
SQL database
Public IP address
Network security group
Service Bus Namespace
Virtual network
Bastion
Network Watcher
Logic app
Logic App (Standard)
Application Insights
Integration account
App Service
Azure Database for MySQL flexible server
Private DNS zone
Synapse workspace
Automation Account
Dedicated SQL pool
Key vault
Analysis Services
Azure DevOps organization


David Monk
Cloud Architect – Cloud Transformation

**Comment by Claudio-Merola** [comment]
I've been trying to think of any case that may cause that issue. 

But so far I cannot see any reason for that to happen. I have try the same versions, a similar environment size, similar type of resources but it always works.

Since we are getting a newer version of the script ready, I believe the best approach would be to wait for the newer version to be release and see how it behaves in that environment.
