### ISSUE TITLE
Add more feature for RAM information 

### ISSUE THREAD

**Issue by basantkc** [microsoft/ARI#109]
Hi Team,
For a long time am using this ARI and am very happy with it- is it possible to add get RAM/Memory information as well? 

Thanks

**Comment by Claudio-Merola** [comment]
Hello,

First of all, thanks for using the tool!

Regarding adding RAM information, I suppose you are talking about the VM and VMSS sheets right? It would be somehow possible, but it would be necessary to add extra API calls to Azure.

Right now Resource Graph only provides the VM size (i.e: Standard_D2_v3), to find the memory and vCPU it would require to consult a separated API just for that. For small environments it would not be a very heavy process, but for larger environments it might impact the overall speed of the report.

Performance is always some of our priorities, so it would be somehow possible, but we would have to validate and test how much it will impact on performance. We are planning to add some extra API call in the next version, so this is something we might consider add as well.

**Comment by Claudio-Merola** [comment]
Hello,

I just approved a PR from Seppohto that addes CPU and RAM information to VM sheet.
