### ISSUE TITLE
Diagram stuck at 50%

### ISSUE THREAD

**Issue by cladaw** [microsoft/ARI#112]
When scaling up to a MG with multiple SUs, diagram run gets stuck at 50%. Works fine with fewer SUs.

Can't figure this one out. Any idea?

![image](https://user-images.githubusercontent.com/91733099/231090781-695cb547-7834-4524-b4df-17db5099b817.png)

**Comment by Claudio-Merola** [comment]
Hello,

Is this a big environment? 

The diagram is done by a single powershell job, by my experience in bigger environments it takes a long time to finish, but in really large environments it might get stuck, I haven't figured why.

We are considering some options to work this out in the new version of the script, perhaps creating separate files during the diagram and then merging them at the end. But for now we don't have a workaround for that problem :(

**Comment by cladaw** [comment]
Ok, thanks for the quick reply on this. 

Not that big, some thousands of resources in total. I'll play around and see if I can find a limit.

**Comment by Claudio-Merola** [comment]
Hello,

Just release the version 3.0, now the diagram should work in that environment. 

Can you please try that version and let me know?

Thanks

**Comment by cladaw** [comment]
Verified and functionality works now. Even with quite large environment. 

However, I have encountered another issue with new Organization view.

Diagram doesn't seem to populate all subscriptions correctly if mgmt. group structure pass 4 levels of depth. Works only up to 3 levels.

Example 1
Root(0) -> LZ(1) -> Corp(2) -> PurposeY(3) -> SubscriptionY

SubscriptionY does not get populated on diagram. 

Example 2
Root(0) -> LZ(1) -> Corp(2) -> SubscriptionX
Subscription X gets populated correctly.

Data do exists on report.

**Comment by Claudio-Merola** [comment]
Hi, Glad it worked!

About the Organizational view, by now it only goes till level 3, you are correct.

I'll see If I can improve that in the following weeks.

**Comment by Claudio-Merola** [comment]
Hello,

Organizational view should cover 4th depth level now.

Can you try?

**Comment by cladaw** [comment]
> Hello @cladaw,
> 
> Organizational view should cover 4th depth level now.
> 
> Can you try?

Subscriptions are being populated on the diagram, but error with properties while adding subscription name on container4

![image](https://github.com/microsoft/ARI/assets/91733099/1ca425ca-74e2-4f46-8cd2-7d4fab4efd33)

**Comment by cladaw** [comment]
> Hello @cladaw,
> 
> That was a bug, thanks for testing. It should be fixed now, can you try?

Verified, works now. Much appreciated for the quick fix!
