### ISSUE TITLE
Public IPs Underutilized erroneously reported

### ISSUE THREAD

**Issue by sjbravent** [microsoft/ARI#115]
Hello,

I have noticed that if the public IP is associated to a NAT Gateway it appears as "Underutilized".

I would like to contribute any additional information to help resolve this.

Thank you very much for maintaining this fabulous tool,

**Comment by Claudio-Merola** [comment]
Hello,

Thanks from bringing that up. 

Let's try something, can you navigate to some of those IPs and click in the "JSON View".

Then, under "properties", can you see any reference to the NAT Gateway there?

Thanks

**Comment by sjbravent** [comment]
Hi Claudio,

Thanks for reply, I attach an example of JSON View:


`{
    "name": "name",
    "id": "/subscriptions/id/resourceGroups/rgname/providers/Microsoft.Network/publicIPAddresses/pipname",
    "etag": "W/\"xxxx\"",
    "location": "westeurope",
    "tags": {},
    "properties": {
        "provisioningState": "Succeeded",
        "resourceGuid": "xxxx",
        "natGateway": {
            "id": "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/natGateways/xxxx"
        },
        "ipAddress": "20.x.x.x",
        "publicIPAddressVersion": "IPv4",
        "publicIPAllocationMethod": "Static",
        "idleTimeoutInMinutes": 4,
        "ipTags": []
    },
    "type": "Microsoft.Network/publicIPAddresses",
    "sku": {
        "name": "Standard"
    }
}`

I can see:

        "natGateway": {
            "id": "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/natGateways/xxxx"
        },

Regards

**Comment by Claudio-Merola** [comment]
Hello,

Thanks for the reply.

I just release the version 3.0 of the script, this issue should be fixed.

Can you download that version of the script and try it out?

Thanks
