### ISSUE TITLE
Runbook ARI IncludeTags

### ISSUE THREAD

**Issue by MasterFatuco** [microsoft/ARI#120]
I wanted to know if there is any possibility to launch ARI through a runbook with the -IncludeTags parameter present in a script launched in PowerShell, to present the inventory with tags.

**Comment by Claudio-Merola** [comment]
Hello,

I just included the following at line 39 of the automation script:

#Include Tags
$InTag = $false

You must change it to: 

$InTag = $true

I believe that should do the trick, please try out and let me know.
