### ISSUE TITLE
Issues with Excel being empy

### ISSUE THREAD

**Issue by MaloSparky** [microsoft/ARI#122]
Even after upgrading I have run into a issue with a machine with a Sensitivity Lable requirement on our excel files, is there a way to successfully run this with Sensitivity labels required by policy? (works on my non-domain joined VDI)

**Comment by Claudio-Merola** [comment]
Hello @MaloSparky 

I think I might have an idea of what is going on in your case, can you just confirm what are the symptoms you are seeing?

The script runs normally and when you try to open the Excel file they are empty? Or there is an error message during the execution of the script?

Perhaps an error in the final parts of the script?

**Comment by MaloSparky** [comment]
@Claudio-Merola Yes everything appears to run =, and then the Excel is blank. I did a bit of variable checks and the resource counts seem to be about right.

**Comment by Claudio-Merola** [comment]
@MaloSparky 

I added a new parameter called "-Lite", can you download the version 3.0.11 of the script and give a try using that parameter?

It should break the Overview sheet, but the content of the excel should work.

Most of the script uses the Import-Excel module which does not relies on Excel API to work. That part I believe is working fine.

I believe the problem in your case is that the last part of the script uses the APIs to create the charts, and I think the policies are being applied at that time. The -Lite parameter will skip that.
