### ISSUE TITLE
ARI Report creates empty squares in overview tab

### ISSUE THREAD

**Issue by s4addict** [microsoft/ARI#125]
When opening the excel spreadsheet the overview tab is all blank squares with no data within them except for one showing over all resources. 

![image](https://github.com/microsoft/ARI/assets/44248239/5afb416b-d3a3-40a3-9672-1052e5e896bb)

I am running this on an azure automation account following the steps to setup the automation account and the account its self has reader rights at the tenant level. 

I do see the following errors when looking at the job within the automation account. 

Failed autosizing columns of worksheet 'Event Hubs': Exception calling "AutoFitColumns" with "0" argument(s): "The type initializer for 'Gdip' threw an exception."

InvalidOperation: C:\usr\src\PSModules\ImportExcel\Public\Export-Excel.ps1:654 Line | 654 | … if (-not $s.Range) { $s["Range"] = $ws.Dimension.Address } | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | Cannot index into a null array.

Hopefully someone has seen this issue before and its just something silly I missed.

**Comment by Claudio-Merola** [comment]
Hi @s4addict 

I updated the ARI_Automation.ps1 to version 3.02, it should address that issue. 

Can you update your automation script with that version and see if the issue is fixed?

**Comment by s4addict** [comment]
Hello Claudio. 

I tried version 3.02 within my automation account and I still get the blank squares. Ideally these would be populated so I can pass the report along. 

![image](https://github.com/microsoft/ARI/assets/44248239/9d444b61-da9e-4e80-929f-e0443091ca57)

**Comment by Claudio-Merola** [comment]
Hi @s4addict 

Did you clicked in the "Enable Editing"?

I have that behavior before I enable the editing of the Excel file, after that the other charts appear.

**Comment by s4addict** [comment]
Hello Claudio. 

Not going to lie im kinda mad at myself for not trying that before I created the issue. Enabling editing fixed the document for me. 

Thank you and sorry for the user issue on my end haha..
