### ISSUE TITLE
Issue:  APP Gateway incorrectly showing WAF disabled

### ISSUE THREAD

**Issue by tc-mgriff** [microsoft/ARI#127]
Looks like the script isn't taking into account the newer WAF configuration through code? We are running WAF_v2 and its incorrectly showing the WAF as disabled, so I'm assuming the value showing its enabled is different than the older version.

**Comment by Claudio-Merola** [comment]
Hi @tc-mgriff 

You are right, I just updated the AppGtw module. 

Can you download that version and give it a try?

**Comment by tc-mgriff** [comment]
its fixed, i pulled the most recent version and it shows the correct status. thank you!
