### ISSUE TITLE
Issue: -IncludeTags argument created duplicates

### ISSUE THREAD

**Issue by tc-mgriff** [microsoft/ARI#128]
When using the -IncludeTags argument it creates a duplicate line for every tag value. This was apparent on the Load Balancers tab, where the correct amount of resources is 10, but with 6 tags it created 60 resources because it created a duplicate line for each tag.

**Comment by Claudio-Merola** [comment]
Hi @tc-mgriff 

This is expected, there will be a line for every tag of every resource.
