### ISSUE TITLE
Functions App missing

### ISSUE THREAD

**Issue by mahfathymahmoud** [microsoft/ARI#134]
the script doesn't export (CDN and Function App) and I also noticed that some Key Vaults are missing however I have contribute role on them

**Comment by Claudio-Merola** [comment]
Hi @mahfathymahmoud,

Function App is reported inside the App Service sheet. I believe we don't do CDN yet...

The Key Vaults missing is odd. Can you check if the missing ones have the same type "microsoft.keyvault/vaults" ?
