### ISSUE TITLE
Some Private IPs are missing in Virtual Machine

### ISSUE THREAD

**Issue by fwdjeffpang** [microsoft/ARI#137]
We recently upgraded from v2 to v3, and found that some of the Private IPs are missing in Virtual Machine tab.
Checked the VM is running from Azure Portal.

Attached please find the screenshot.
<img width="1594" alt="Screenshot 2023-07-25 at 16 16 53" src="https://github.com/microsoft/ARI/assets/107546484/87eb0bd6-e105-4ac8-949b-b290e7422a52">

**Comment by Claudio-Merola** [comment]
Hi @fwdjeffpang 

That particular part was not changed from previous version.

Can you try another time after upgrading the Az Cli modules and extensions and using the -Debug parameter to give us more insights?
