### ISSUE TITLE
I am having 29667 resource and the powershell is getting stuck

### ISSUE THREAD

**Issue by ashrafcitius** [microsoft/ARI#140]
While executing the powershell script the script is getting stuck, i have around 29667 resources, i does generate an excel sheet but it has missed a lot of things even its showing error regarding Pivot tables also it does generate any xml diagram sheet, please suggest what can be done?

**Comment by Claudio-Merola** [comment]
Hello @ashrafcitius 

Where are you running the script? CloudShell, Windows 11 client computer, Mac?

Can you try to run the script with -Debug and -Lite parameters to see how it goes?

I have seen some problems when you do have some different types of resources with too many details in the properties for example

**Comment by ashrafcitius** [comment]
It gets stuck at 

DEBUG: Starting subscription job
DEBUG: Starting processing job
DEBUG: Starting jobs collector
DEBUG: Jobs still running:30
DEBUG: Jobs still running:30

And then it just continues to show the same after sometime it just get stuck.

**Comment by Claudio-Merola** [comment]
I believe I know what might be happening, I think it is starting too much processes to handle the load...

I just uploaded a version 3.1.06, can you try it using the new parameter -Heavy?

**Comment by ashrafcitius** [comment]
Do you meant to say > .\AzureResourceInventory.ps1 -Heavy -Debug 

because i can see under the script there is a parameter as $HeavyLoad so should i mention -HeavyLoad or -Heavy?

**Comment by ashrafcitius** [comment]
I tried to execute > .\AzureResourceInventory.ps1 -Heavy -Debug -Lite and now it is stuck at below.

DEBUG: Jobs still running: 6

just FYI it did hit the Heavy parameter that you have written.

**Comment by Claudio-Merola** [comment]
sorry, is -HeavyLoad

Can you download the version 3.1.07 and give it a try?

Thanks

**Comment by ashrafcitius** [comment]
As you said i download the 3.1.07 and executed it with -HeavyLoad and now i am stuck as you can see below:

Seems like its taking time to process the resources and that is where it just get stuck as it contains a lot of properties and Resources.

DEBUG: Excel file:C:\AzureResourceInventory\AzureResourceInventory_Report_2023-08-28_19_24.xlsx
DEBUG: Excel Table Style used: Light19
DEBUG: Importing List of Unsupported Versions.
DEBUG: Looking for the following file: https://raw.githubusercontent.com/microsoft/ARI/main/Extras/Support.json
DEBUG: Checking if Draw.io Diagram Job Should be Run.
DEBUG: Starting Draw.io Diagram Processing Job.
DEBUG: Checking If Should Run Security Center Job.
DEBUG: Checking If Should Run Policy Job.
DEBUG: Starting Policy Processing Job.
DEBUG: Checking If Should Run Advisory Job.
DEBUG: Starting Advisory Processing Job.
DEBUG: Starting Subscriptions job.
DEBUG: Starting Processing Jobs in Heavy Mode.
DEBUG: Starting Jobs Collector.
DEBUG: Jobs Still Running: 7
DEBUG: Jobs Still Running: 7
DEBUG: Jobs Still Running: 7
DEBUG: Jobs Still Running: 7
DEBUG: Jobs Still Running: 7
DEBUG: Jobs Still Running: 7
DEBUG: Jobs Still Running: 7
DEBUG: Jobs Still Running: 7
DEBUG: Jobs Still Running: 7
DEBUG: Jobs Still Running: 7
DEBUG: Jobs Still Running: 7
DEBUG: Jobs Still Running: 7
DEBUG: Jobs Still Running: 7

**Comment by ashrafcitius** [comment]
As you said I left it as it is for hours but the job did not get reduced also my CPU utilisation was 100% because of which my system itself got stuck.

**Comment by Claudio-Merola** [comment]
The processing power of you computer is not being able to handle that load.

I tried to add some extra resources in the script to slow a little bit the processing speed. it might take more time, perhaps some hours to complete, but I hope it will eventually not get stuck at 100%. 

Try to download the last version and run with -HeavyLoad. 

But if that do not work I'm afraid there is not going to be much else to do from this side.
