### ISSUE TITLE
Get-AzContext does not gather all the subscriptions

### ISSUE THREAD

**Issue by gerardjongh** [microsoft/ARI#143]
Get-AzContext does not gather all the subscriptions for me
Instead i have to use Get-AzSubscription.

So lines 97 and 98 can be replaced by
`$Subscriptions = Get-AzSubscription | Where-Object {$_.State -ne 'Disabled'}`

**Comment by Claudio-Merola** [comment]
Hi @gerardjongh 

We use az CLI to get the subscriptions, at line 307 with "az account list"

What version of the script are you running? In the past we tried to use powershell for that, but ended up leading to many problems, so we changed back to az cli

**Comment by gerardjongh** [comment]
> Hi @gerardjongh
> 
> We use az CLI to get the subscriptions, at line 307 with "az account list"
> 
> What version of the script are you running? In the past we tried to use powershell for that, but ended up leading to many problems, so we changed back to az cli

Hi @Claudio-Merola,
Sorry, i was not quite clear in my comment, but i am using the Azure Automation version (in an automation account).
So i am talking about the Automation/ARI_Automation.ps1

So i think in that script the lines 97 and 98 can be replaced by
$Subscriptions = Get-AzSubscription | Where-Object {$_.State -ne 'Disabled'}

**Comment by Claudio-Merola** [comment]
Hi @gerardjongh ,

Oh, I see, now it makes sense lol

I made the change in the script. Thanks for the heads up
