### ISSUE TITLE
It does not export if I include the -ResourceGroup flag.

### ISSUE THREAD

**Issue by MiguelMaestro** [microsoft/ARI#144]
It does not export if I include the -ResourceGroup flag.

![zt2WTJeyyu](https://github.com/microsoft/ARI/assets/105984434/698a04bf-70ac-409b-83a7-6acbd9eabf1b)

The excel is empty

[ari_demo_Nitro_pro_01_Report_2023-09-07_11_33.xlsx](https://github.com/microsoft/ARI/files/12547257/ari_demo_Nitro_pro_01_Report_2023-09-07_11_33.xlsx)

Thanks in advance
```[tasklist]
### Tasks
```

**Comment by davymartu** [comment]
Hi, I found that if you include -ResourceGroup flag, you have to insert your resource group name in lower case because all resourceGroup in azure graph are in lower case.
Thanks 
Davide

**Comment by Claudio-Merola** [comment]
Hi @MiguelMaestro , 

as @davymartu mentioned, resourcegroups have to be passed in lower case. Indeed all the resources are converted to lower case in the script.

we made this as a workaround for a bug that exists when extracting some specific resources to powershell from resource graph.
