### ISSUE TITLE
IP addressess in wrong format

### ISSUE THREAD

**Issue by crimez** [microsoft/ARI#147]
In the "public IPs" sheet the format of the IPs is not intelligible

![image](https://github.com/microsoft/ARI/assets/16936343/da8f923a-2181-4a7c-b8e4-70cf24104c99)

**Comment by Claudio-Merola** [comment]
I updated the PublicIP module. Can you try the last version?

Thanks

**Comment by crimez** [comment]
I made a mistake by passing a misspelled argument, the "public IP" fix
works like a charm.
Thanks

Christian

Il giorno mar 7 nov 2023 alle ore 10:38 I Cucciolini ***@***.***>
ha scritto:

**Comment by Claudio-Merola** [comment]
Glad it worked.

Thanks
