### ISSUE TITLE
IP address strings are converted in numbers

### ISSUE THREAD

**Issue by davymartu** [microsoft/ARI#151]
Hi team, 
I've a problem generating worksheets of my resources on IP Addresses that are converted in numbers by  #ImportExcel.
I think that could be a regional settings related issue.
I'm using Italian regional settings on my PC with Digit grouping symbol is dot 

I found e [here](https://github.com/dfinke/ImportExcel/issues/188) a workaround on ImportExcel related issue  
or [here](https://github.com/dfinke/ImportExcel/issues/1499) with the same suggestion
I will made a pull request for It 

I didn't find the way to force a column format to string (something like Set-Format or Set-ExcelColumn -type string)
I saw that data fetched from Azure is already cast in string
`'IP Address'               = [string]$data.ipAddress;`

Thanks in advance 
Davide

**Comment by crimez** [comment]
I think you are right because I didn't get the same behavior on all PCs I ran the script on, they probably have different regional settings
