### ISSUE TITLE
ThreadJob NotStarted

### ISSUE THREAD

**Issue by BrunoSuicida** [microsoft/ARI#155]
Hello i am a newbie when it comes to Powershell, but i have installed all required modules and i cannot get ThreadJob to start, which means that it always reports every value as "0" and creates an empty xlsx. I have made a few modifications on the code to suit my needs but it also happens on the default ps1.  I'm using the automation PS1.

Any idea why this is happening? I tried to find some answers online and checked the previous issues but couldn't find any. Sorry if it's a "simple issue".

**Comment by Claudio-Merola** [comment]
Olá @BrunoSuicida 

vc chegou a adicionar os modulos na Automation Account? E esta utilizando runtime 7.2?

**Comment by BrunoSuicida** [comment]
Sim os 5 modulos foram adicionados e esta a usar o 7.2, a questao é que o ThreadJob nao inicia e nao faz muito sentido nao iniciar sendo que nao alterei nada nessa parte do codigo, so fiz alteracoes no $file, para dar um nome diferente, no upload para criar um blob folder e meti o script dentro de um "foreach" porque o automation é para correr em varias subscricoes (a automation account tem acesso ao Management Group que inclui-as todas)

**Comment by Claudio-Merola** [comment]
Mas o script já vai executar em todas as subscriptions

**Comment by BrunoSuicida** [comment]
Sim eu sei, mas eu queria que ele fizesse um Excel por cada, para ter uma listagem de recursos independente e no final fazer um de todas as subscricoes, oposto a um só um com todas as subscriçoes

**Comment by Claudio-Merola** [comment]
Vc chegou a dar as permissões para a identidade da Automation Account?

**Comment by BrunoSuicida** [comment]
Sim, mas para o que se queria ja deu, porque basicamente ele esta a correr por subscricao em vez de fazer um excel com todas. Esse nao consegui meter a correr mas de resto ta tudo 5*
