### ISSUE TITLE
Please remove the function that delete Excel files in the specified report directory

### ISSUE THREAD

**Issue by frankherrmann-github** [microsoft/ARI#158]
Please ensure that all previous files in the report directory are retained.
I have stored many analysis Excel files there - now they are gone

.\AzureResourceInventory.ps1 -TenantID xxxxxxxxxxxxxxxxxxx -Online -SkipAdvisory -ReportDir "C:\private\Powershell\XLSExports" -Diagram -DiagramFullEnvironment

**Comment by VisFGO** [comment]
hello you can add an option > delete or not 
personally i use this delete function
thanks

**Comment by Claudio-Merola** [comment]
Hello,

Actually the script does not delete the previous Excel or XML files from the root folder. 

This is actually happening to you?

**Comment by shadowarmor** [comment]
Can confirm the same behaviour when using "-ReportDir", if I dont specify the report output dir it obviously goes to the default folder output, but I actually get my complete network diagram as well apposed to only getting a two pager, so by specifying the output directory, it strips pages from the draw.io xml, funny enough, when I watch the folder I can see more individual pages being created and then they disappear and im left with scraps in the final report xml file. I have the latest packages installed as per README and also using this latest ARI. -Hope this helps.

**Comment by Claudio-Merola** [comment]
Hi @shadowarmor 

This was a bug. We just fixed that in the version 3.1.13, can you try it?
