### ISSUE TITLE
Automation Account Problem

### ISSUE THREAD

**Issue by MaximilianoGutierrez** [microsoft/ARI#160]
Hello, I've been testing both scripts. Running locally works just fine but the Automation Account Script isn't working. 

These are the error messages I've got:

InvalidOperation: C:\usr\src\PSModules\ImportExcel\Public\Set-ExcelRange.ps1:107 Line | 107 | … $Range.Style.HorizontalAlignment = $HorizontalAlignment | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | The property 'HorizontalAlignment' cannot be found on this object. Verify that the property exists and can be set.

InvalidOperation: C:\usr\src\PSModules\ImportExcel\Public\Set-ExcelRange.ps1:128 Line | 128 | … $Range.Style.Numberformat.Format = (Expand-NumberFormat $ … | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | The property 'Format' cannot be found on this object. Verify that the property exists and can be set.

InvalidOperation: Line | 134 | $User = $Subscriptions[0].user.name | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | Cannot index into a null array.

I guess this problem happens because the results are empty:

Environments                                                                                           Context
------------                                                                                           -------
{[AzureUSGovernment, AzureUSGovernment], [AzureChinaCloud, AzureChinaCloud], [AzureCloud, AzureCloud]} Microsoft.Azure.…

Extracting Advisories

Extracting Resources

Starting Advisory Job

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
1      Advisory        ThreadJob       Running       False           PowerShell           <#…

Starting Subscription Job

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
2      Subscriptions   ThreadJob       NotStarted    False           PowerShell           <#…

Starting Resources Processes

Resources (Databricks): 0

Resources (EvtHub): 0

Resources (MachineLearning): 0

Resources (Streamanalytics): 0

Resources (Synapse): 0

Resources (WrkSpace): 0

Resources (APPSERVICEPLAN): 0

Resources (APPSERVICES): 0

Resources (ARCServers): 0

Resources (ARO): 0

Resources (AVD): 0

Resources (CloudServices): 0

Resources (VM): 0

Resources (VMWare): 0

Resources (AKS): 0

Resources (CONTAINER): 0

Resources (REGISTRIES): 0

Resources (VMSS): 0

Resources (CosmosDB): 0

Resources (MariaDB): 0

Resources (MySQL): 0

Resources (MySQLflexible): 0

Resources (POSTGRE): 0

Resources (Purview): 0

Resources (RedisCache): 0

Resources (SQLDB): 0

Resources (SQLMI): 0

Resources (SQLMIDB): 0

Resources (SQLPOOL): 0

Resources (SQLSERVER): 0

Resources (SQLVM): 0

Resources (AppGW): 0

Resources (AutomationAcc): 0

Resources (AvSet): 0

Resources (BASTION): 0

Resources (Frontdoor): 0

Resources (RecoveryVault): 0

Resources (Vault): 0

Resources (APIM): 0

Resources (AppInsights): 0

Resources (IOTHubs): 0

Resources (ServiceBUS): 0

Resources (AzureFirewall): 0

Resources (Connections): 0

Resources (ExpressRoute): 0

Resources (NATGAteway): 0

Resources (NetworkSecurityGroup): 0

Resources (PrivateDNS): 0

Resources (PublicDNS): 0

Resources (PublicIP): 0

Resources (ROUTETABLE): 0

Resources (TrafficManager): 0

Resources (VNETGTW): 0

Resources (VirtualNetwork): 0

Resources (VirtualWAN): 0

Resources (vNETPeering): 0

Resources (DataExplorerCluster): 0

Resources (NetApp): 0

Resources (StorageAcc): 0

Resources (VMDisk): 0

Uploading Excel File to Storage Account

Completed

**Comment by ega1973** [comment]
After some debugging, I commented the line $Subscriptions = $Subscriptions.Subscription in file ARI_Automation.ps1 and I could generate the inventory xls file with the automation account

**Comment by MaximilianoGutierrez** [comment]
> After some debugging, I commented the line $Subscriptions = $Subscriptions.Subscription in file ARI_Automation.ps1 and I could generate the inventory xls file with the automation account

Hello!, I've found the same fix. Thanks for the response!

**Comment by MaximilianoGutierrez** [comment]
Commenting the line $Subscriptions = $Subscriptions.Subscription solvde the issue.
