### ISSUE TITLE
Add List Reserved Intances resources with their use ?

### ISSUE THREAD

**Issue by VisFGO** [microsoft/ARI#161]
hello 
can you add List of Reserved Intances resources with their use ? and capacity plan?
thanks

**Comment by Claudio-Merola** [comment]
Hello @VisFGO ,

unfortunately Reserved Instances require a different set of permissions to be presented. 


It could be possible to include that in the report if the required permissions were granted to the person running the script. We might include this feature in future versions, but for now that is not planned.
