### ISSUE TITLE
Trying to use Service Principal Authentication Method in a wrong way

### ISSUE THREAD

**Issue by luisfarin** [microsoft/ARI#162]
Hello, 
I'm lauching ARI with -TenantID and -SubscriptionID set. I have Reader role on the same. 
I get the following output:

```
Validating Az Cli..
Validating Az Cli Extension..
Validating ImportExcel Module..
PowerShell Desktop Identified.

Azure Cloud Environment: AzureCloud
You are trying to use Service Principal Authentication Method in a wrong way.
It's Mandatory to specify Application ID, Secret and Tenant ID in Azure Resource Inventory

.\AzureResourceInventory.ps1 -appid <SP AppID> -secret <SP Secret> -tenant <TenantID>
```

Can you please clarify (and document) under which conditions Service Principal Authentication is not applicable? and how appID and Secret should be configured?

With another Tenant/subscription the execution completed successfully (and I think the output is great and very interesting to investigate further!)

Many thanks for support!

Luisa

**Comment by Claudio-Merola** [comment]
Hello @luisfarin 

How are you using the Service Principal parameters in the script execution?

In the environment the execution runs correctly, are you using service principal?

**Comment by luisfarin** [comment]
> Hello @luisfarin
> 
> How are you using the Service Principal parameters in the script execution?
> 
> In the environment the execution runs correctly, are you using service principal?

Hello @Claudio-Merola ,
I logged in with my user-id as mentioned here and run the script with -TenantID and -SubscriptionID only. Is -Secret mandatory? or how should I use the service principal? I have no doubts that it works in your env, I was rather pointing out to better clarify in the "how-to" since I did not find any guidance :-) thanks!
