### ISSUE TITLE
Feature Request: Use GitHub Releases

### ISSUE THREAD

**Issue by dloos-ctac** [microsoft/ARI#165]
Hi,

It would be great if the GitHub release functionality (https://docs.github.com/repositories/releasing-projects-on-github/about-releases) was used for easy incorporation within e.g. pipelines.

Keep up the good work!

Kind regards,
Dennis Loos.

**Comment by Claudio-Merola** [comment]
Hi @dloos-ctac 

We used releases loooong time ago, but it was a very different process. Now seems the process is a lot easier and better.

I'll try to remember to use it every new release. Thanks for the tip.
