### ISSUE TITLE
Privatelink IPs

### ISSUE THREAD

**Issue by wingcomm** [microsoft/ARI#166]
This tool is AMAZING. Thank you for building it. Can we include the Privatelink IPs in use either as a separate tab or include them as a column on the resources to which they are bound?

**Comment by Claudio-Merola** [comment]
Hi @wingcomm,

That's a good idea. I just added it. 

Can you try the script now? should be a new sheet name PvtEndpoint

Thanks

**Comment by wingcomm** [comment]
Great! I did test it. It picked up our ARC private endpoint however it was unable to enumerate the private Endpoint IP Address tied to the NIC on our Azure SQL server.

**Comment by Claudio-Merola** [comment]
@wingcomm 

For some reason some private endpoints don't have that information in place, I believe it has something to do with the date those private endpoint were created, anyways I managed to get that information from somewhere else and it should be fine now. 

Can you try it and let me know if it works?

**Comment by wingcomm** [comment]
@Claudio-Merola That worked! Thank you! We'll test with some more endpoints.

**Comment by drangelc** [comment]
@Claudio-Merola Thanks for the new functionality! It works fine for me too, except that the IPs addresses appear without the dots. In other tabs, the IPs appear fine.

**Comment by wingcomm** [comment]
@drangelc I am not seeing that behavior at all. All of my IPv4s use fully dotted notation.

**Comment by drangelc** [comment]
> @drangelc I am not seeing that behavior at all. All of my IPv4s use fully dotted notation. (e.g. 1.2.3.4)

In my case, the format is wrong

![image](https://github.com/microsoft/ARI/assets/110741486/f2c45c9e-af77-47de-849d-fd6ce6cee57f)

In other sheets it's correct

![image](https://github.com/microsoft/ARI/assets/110741486/7a58f4c4-dcd4-4bd6-9d36-840cbf66795f)

**Comment by Claudio-Merola** [comment]
@drangelc, I assume your Excel is converting the cell to number instead of general, can you check that? Also I believe there are some O.S configurations that might cause that behavior.

@wingcomm, what you mean? The Private Endpoint sheet is missing the IPs for some Private Endpoint?

**Comment by wingcomm** [comment]
@Claudio-Merola 

When I navigate here I see 10 Private Endpoint IPs : https://portal.azure.com/#view/HubsExtension/BrowseResource/resourceType/Microsoft.Network%2Fnetworkinterfaces

The Excel spreadsheet generated by ARI only lists 2.

It looks like we're missing of Virtual Machine private IPs.

**Comment by Claudio-Merola** [comment]
@wingcomm 

But Network Interfaces are different resource types than Private Endpoints. When you go to: https://portal.azure.com/#view/Microsoft_Azure_Network/PrivateLinkCenterBlade/~/privateendpoints

Do you see the same number of the Excel sheet?

**Comment by wingcomm** [comment]
Got it. I guess my end goal is to document all Private IP Usage on Azure Virtual Networks. Would this be better suited to a different sheet?

**Comment by Claudio-Merola** [comment]
@wingcomm 

Like what you get in the "connected devices" in the VNET?

**Comment by wingcomm** [comment]
> @wingcomm
> 
> Like what you get in the "connected devices" in the VNET?

Correct, across all VNETs or by VNET.

**Comment by drangelc** [comment]
I have checked the format and it is correct. The strangest thing is that, if the private endpoint has more than one IP, it appears fine. I attach an example.
![image](https://github.com/microsoft/ARI/assets/110741486/ae3f4884-6608-412a-bfd3-00bc3a1f3706)
