### ISSUE TITLE
fails to create report

### ISSUE THREAD

**Issue by Pieterle-Roux** [microsoft/ARI#168]
excel report fails to build 
![ari error](https://github.com/microsoft/ARI/assets/160742410/4309580e-8237-44c1-91e6-854425a77000)
with a message "we couldn't complete the action for the pivot table "P2" in the sheet "overview" because there's already a table or XML map "azure tabs" there. Make space and try again.

second error also comes up "we couldn't complete the action for the pivot table "P0" in the sheet "overview" because there's already a table or XML map "azure tabs" there. Make space and try again.

**Comment by Pieterle-Roux** [comment]
has anyone else experienced this failure to build the spreadsheet ?

**Comment by Claudio-Merola** [comment]
Hello @Pieterle-Roux 

Do you see any error during the script execution using the -Debug parameter?

**Comment by Pieterle-Roux** [comment]
Hi Claudio-Merola

this is what I get under the -debug

Get-Job : Cannot validate argument on parameter 'Name'. The argument is null, empty, or an element of the argument collection contains a null value. Supply a collection that does not contain any null 
values and then try the command again.
At C:\Resource inventory script\ARI-main V3.1.7\AzureResourceInventory.ps1:1377 char:30
+         while (get-job -Name $JobNames | Where-Object { $_.State -eq  ...
+                              ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-Job], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.GetJobCommand
![debug](https://github.com/microsoft/ARI/assets/160742410/f39dae07-e3d0-4ca4-94b1-5bce2f23e5eb)

**Comment by Claudio-Merola** [comment]
@Pieterle-Roux 

apparently the script is failing to extract the resources from your environment.

Do you have all the requirements installed? (i.e: resource-graph az cli extension)

Are you running the script in Windows Powershell or Powershell Core?

**Comment by Pieterle-Roux** [comment]
this is the only error I get when running in -debug mode
![debug 2](https://github.com/microsoft/ARI/assets/160742410/aba061e2-b0a2-4fed-967d-b7aad5e5f7b5)

**Comment by Pieterle-Roux** [comment]
then it gets to building the report and hangs on 50% progress and eventually becomes unresponsive
![powershell](https://github.com/microsoft/ARI/assets/160742410/02a8a1c0-fc2f-49cc-8aec-4e8b30b68aeb)

**Comment by Claudio-Merola** [comment]
@Pieterle-Roux 

Would you be able to to run the script on Powershell Core?

**Comment by Pieterle-Roux** [comment]
seems to run under powershell core but only if I add the switch -SkipSecurityCenter as soon as I include -securitycenter it reaches 50% and then hangs again
![securitycenter](https://github.com/microsoft/ARI/assets/160742410/053d9234-834a-4af8-8b43-6f378d66033b)

**Comment by Pieterle-Roux** [comment]
DEBUG: Checking If Should Run Security Center Job.                                                                                                                                              DEBUG: Starting Security Job.                                                                                                                                                                   DEBUG: Checking If Should Run Policy Job.                                                                                                                                                       DEBUG: Starting Policy Processing Job.                                                                                                                                                          DEBUG: Checking If Should Run Advisory Job.                                                                                                                                                     DEBUG: Starting Advisory Processing Job.                                                                                                                                                        DEBUG: Starting Subscriptions job.                                                                                                                                                              DEBUG: Starting Processing Jobs in Regular Mode.                                                                                                                                                DEBUG: Starting Jobs Collector.                                                                                                                                                                 Get-Job : Cannot validate argument on parameter 'Name'. The argument is null, empty, or an element of the argument collection contains a null value. Supply a collection that does not contain  any null values and then try the command again.                                                                                                                                                 At C:\Resource inventory script\ARI-main V3.1.7\AzureResourceInventory.ps1:1377 char:30                                                                                                         +         while (get-job -Name $JobNames | Where-Object { $_.State -eq  ...                                                                                                                     +                              ~~~~~~~~~                                                                                                                                                            + CategoryInfo          : InvalidData: (:) [Get-Job], ParameterBindingValidationException                                                                                                       + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.GetJobCommand   
![debug3](https://github.com/microsoft/ARI/assets/160742410/5a85fd92-12d9-4611-a0d3-8c977f7ff7f1)

**Comment by Pieterle-Roux** [comment]
Sorry for the late response Claudio

The issue was caused by a recent upgrade to Windows 11 and Group Policies that made changes to my firewall settings, as soon as I disabled the firewall (temporarily) the script completed successfully

Pieter Le Roux
Lead: Cloud
Altron Digital Business
[altron.com digital business website]<https://altron.com/digital-business>
w:
altron.com/digital-business<https://altron.com/digital-business%20>



This document is protected by Altron - labelled as General Business Information
