### ISSUE TITLE
Load Balancer details not available 

### ISSUE THREAD

**Issue by sukhdev-vyash** [microsoft/ARI#173]
Hey Team,

I have used ARI script to fetch the inventory I just noticed most of the azure services are covered but it's not list Azure Load balancer details, is it something some arguments needs to be passed to get these details.

**Comment by Claudio-Merola** [comment]
Hi @sukhdev-vyash 

We disabled the LoadBalancer module in the past due to performance problems. But we haven't been able to improve it yet.

If you don't have many Load Balancers in the environment you can enable the module by renaming the file LoadBalancer.ps2 to LoadBalancer.ps1

**Comment by sukhdev-vyash** [comment]
Thanks for quick update. 

So If I am creating a automation task for this using automation account so in that it will still refrence the main repo for fetching the modules and main does have loadblancer.ps2 which will not execute.

And for local system do I need to create new branch with .ps1 for lb and then update the script to use feature branch for load balancer ?
