### ISSUE TITLE
ARI Security Checks Report Incorrect Recommendation for the Guest Agent

### ISSUE THREAD

**Issue by wingcomm** [microsoft/ARI#174]
While reviewing the ARI XLSX output, we observed that it recommends that the "guest configuration extension should be installed on machines" for VMs that currently have the guest agent installed.

When I go to the identified VM and select Overview -> Virtual Machine I see the following:

![image](https://github.com/microsoft/ARI/assets/9159510/8aae2b47-0def-4681-9565-7bf69693adee)

Am I misunderstanding the recommendation? If so, links to Microsoft Support articles might be helpful.

**Comment by Claudio-Merola** [comment]
Hi @wingcomm 

What do you mean by "Guest Configuration Extension should be installed on machines"? 

The Excel file has 3 columns that might be related to extensions:
![image](https://github.com/microsoft/ARI/assets/108147804/3876ec84-4c51-4b71-b3ca-70b5e38c582e)

At the top of all those columns you can click the column name and it will open the official Microsoft documentation regarding that extension.

**Comment by wingcomm** [comment]
Hi @Claudio-Merola This is on the "Advisory" sheet of the ARI XLSX output. On the problem column, we are seeing "guest configuration extension should be installed on machines" on VMs that have the guest agent installed.

**Comment by wingcomm** [comment]
*bump* to avoid “no issue activity.”

**Comment by Claudio-Merola** [comment]
Hello there @wingcomm,

The Advisory sheet gets information directly from Azure Advisor. It has no relation with the information present in the other sheets
