### ISSUE TITLE
XML not created (State Broken)

### ISSUE THREAD

**Issue by alecorgit** [microsoft/ARI#175]
Hello @Claudio-Merola, I'm creating the Azure Diagrams using the latest version 3.1.13, it works but not for all subscriptions.
When it doesn't work, it hangs at: "_DEBUG: Finished Charts Phase._", "_Building Report - 98% Complete._"
and the xml file is not created.

The parameters used are: _-debug -DiagramFullEnvironment [-SkipAdvisory] [-SkipPolicy] [-HeavyLoad] [-lite]_

The _$Global:Logfile_ by DrawIODiagram.ps1 is also not created, so I guess "**_Extras/DrawIODiagram.ps1_**" isn't called at all.

In AzureResourceInventory.ps1 on line 991 I commented Out-Null

 _} -ArgumentList $PSScriptRoot, $Subscriptions, ($Resources | ConvertTo-Json -Depth 50), $Advisories, $DDFile, $DiagramCache, $FullEnv, $ResourceContainers ,$RunOnline, $Repo, $RawRepo ###  | Out-Null_ 

and now I see the error: 

>**DEBUG: Job ResourceJob_15 Returned: 0 Resource Types.
Opening the remote session failed with an unexpected state. State Broken.
    + CategoryInfo          : OpenError: (localhost:String) [], RuntimeException
    + FullyQualifiedErrorId : PSSessionStateBroken**

 
I don't know if you are able to reproduce this issue, so I tried to provide as much information as possible and hope it helps.

Let me know if there is anything else I can do to figure out why the xml file is not created.

Thank you

**Comment by Claudio-Merola** [comment]
Hi @alecorgit 

I uploaded a version 3.1.14. It does not fix your issues. But now we should be able to see more details on what is going on.

When it stales at "Building Report - 98% Complete." at least you should see the name of the module that the report is getting stuck.

Now the logfile for the diagram should be created every time and I hope it will give some hint of what is going bad during that part.

Also, are you running the script in Powershell Core or Windows Powershell?

Thanks

**Comment by alecorgit** [comment]
Hi @Claudio-Merola, I used Windows PowerShell 5.1 and even using 3.1.14 version, the XML and the log files are not created.
On the same computer I just tried to run the script in 2 different subscriptions that have the issue, using PowerShell 7.4.0

They both get stuck on:

_**DEBUG: Looking for the following file: R:\ARI-AzureResourceInventory\ARI-main\Extras\Charts.ps1
DEBUG: Finished Charts Phase.**_

In the first subscription the XML is created but it is not complete (all the subnets and some vNETs are missing), the log:

```
DrawIOCoreJob - 2024-03-13_09_58_01 - Starting Draw.IO Job
DrawIOCoreJob - 2024-03-13_09_58_01 - Running Local
DrawIOCoreJob - 2024-03-13_09_58_01 - Calling Draw.IO Thread
DrawIOCoreFile - 2024-03-13_09_58_13 - Starting Draw.IO file
DrawIOCoreFile - 2024-03-13_09_58_13 - Setting XML files to be clean
DrawIOCoreFile - 2024-03-13_09_58_13 - Cleaning old files
DrawIOCoreFile - 2024-03-13_09_58_13 - Starting Organization Function
DrawIOCoreFile - 2024-03-13_09_58_13 - Starting Network Topology Function
DrawIONetwork - 2024-03-13_09_58_13 - Starting Network Diagram Job...
DrawIOCoreFile - 2024-03-13_09_58_13 - Starting Subscription Function
DrawIOCoreFile - 2024-03-13_09_58_13 - Waiting for Jobs to complete
DrawIONetwork - 2024-03-13_09_59_17 - Setting Subnet files
DrawIONetwork - 2024-03-13_09_59_17 - Calling Variables0 Function
DrawIONetwork - 2024-03-13_09_59_17 - Waiting Variables Job to complete
DrawIONetwork - 2024-03-13_10_00_19 - Setting Variables
DrawIONetwork - 2024-03-13_10_00_19 - Defining XML file
DrawIONetwork - 2024-03-13_10_00_19 - Calling Stensils
DrawIONetwork - 2024-03-13_10_00_19 - Calling OnPremNet
DrawIONetwork - 2024-03-13_10_02_41 - Calling as FullEnvironment
DrawIONetwork - 2024-03-13_10_04_30 - Waiting Job2 to complete
```


In the second subscription the XML is created with 0KB and it hangs on:

```
DrawIOCoreJob - 2024-03-13_13_14_43 - Starting Draw.IO Job
DrawIOCoreJob - 2024-03-13_13_14_43 - Running Local
DrawIOCoreJob - 2024-03-13_13_14_43 - Calling Draw.IO Thread
DrawIOCoreFile - 2024-03-13_13_14_58 - Starting Draw.IO file
DrawIOCoreFile - 2024-03-13_13_14_58 - Setting XML files to be clean
DrawIOCoreFile - 2024-03-13_13_14_58 - Cleaning old files
DrawIOCoreFile - 2024-03-13_13_14_58 - Starting Organization Function
DrawIOCoreFile - 2024-03-13_13_14_58 - Starting Network Topology Function
DrawIONetwork - 2024-03-13_13_14_58 - Starting Network Diagram Job...
DrawIOCoreFile - 2024-03-13_13_14_58 - Starting Subscription Function
DrawIOCoreFile - 2024-03-13_13_14_58 - Waiting for Jobs to complete
DrawIONetwork - 2024-03-13_13_17_16 - Setting Subnet files
DrawIONetwork - 2024-03-13_13_17_16 - Calling Variables0 Function
DrawIONetwork - 2024-03-13_13_17_16 - Waiting Variables Job to complete
DrawIONetwork - 2024-03-13_13_19_29 - Setting Variables
DrawIONetwork - 2024-03-13_13_19_29 - Defining XML file
DrawIONetwork - 2024-03-13_13_19_29 - Calling Stensils
DrawIONetwork - 2024-03-13_13_19_29 - Calling OnPremNet
```

We can focus and continue troubleshooting using PowerShell 7.

Thanks

**Comment by alecorgit** [comment]
Hi @Claudio-Merola, I did further tests.
I confirm that using Windows PowerShell 5.1 and also using version 3.1.14, the XML and log files are not created for 2 subscriptions.
On the same computer using PowerShell 7.4.0, the XML files and log are created, the longest step is "- Waiting Job2 to complete" and after a few hours the scripts end.

Unfortunately these subscriptions are very large with many objects, the xml file is over 2 MB and at a certain point, viewing the network graph, the peers no longer appear and the VNETs are all crowded together.

I would say that the problem of the xml file not being created and the script not finishing can be solved, for these subscriptions, using PowerShell 7.4.

Thanks

**Comment by Claudio-Merola** [comment]
Hi @alecorgit 

Thanks for the update.

That behavior is VERY strange, I don't see why the script would stall with PS.5 and work with PS.7. 

I suspect some improvements in the way PS.7 deals with long running and big memory consumption threads. but is just a guest

But I'm glad you were able to workaround it with PS.7.
