### ISSUE TITLE
changing the output method from excel to SQL or table storage

### ISSUE THREAD

**Issue by Pieterle-Roux** [microsoft/ARI#181]
How would I run the script so the output is written directly to a SQL database or table storage instead of into excel ?

**Comment by Claudio-Merola** [comment]
Hello there @Pieterle-Roux 

The easiest way I can think if is to change every module to modify the Export-Excel part to input that variable into a SQL db

**Comment by Pieterle-Roux** [comment]
Hi Claudio

Your response is much appreciated.

We managed to do exactly that and we are appending the outputs to the database so we now have the ability to track historical changes as well

regards

Pieter Le Roux
Lead: Cloud
Altron Digital Business
[altron.com digital business website]<https://altron.com/digital-business>
w:
altron.com/digital-business<https://altron.com/digital-business%20>



This document is protected by Altron - labelled as General Business Information
