### ISSUE TITLE
AzureResourceInventory.ps1 has command that causes issues

### ISSUE THREAD

**Issue by TurnerMarshall** [microsoft/ARI#182]
Line 235 and 241 of [ARI](https://github.com/microsoft/ARI/tree/main)/AzureResourceInventory.ps1 have "Get-InstalledModule" instead of "Get-Module"

**Comment by Claudio-Merola** [comment]
Hello there @TurnerMarshall 

If I'm not mistaken, Get-Module does not list modules installed using Install-Module, which is the case of Import-Excel. That is way we choose to use Get-InstalledModule

**Comment by TurnerMarshall** [comment]
Get-module gets all imported and any that are currently in the PSModule paths. If it was imported or sits within those paths it will show. Get-InstalledModule will show PowerShell commands that were installed with PowerShellGet. If you are not in an environment internet connected utilizing PowerShellGet becomes a more difficult task. I was able to just switch the commands in the prompt to get it to work on my end but figured depending on situations Get-Module will always work and Get-InstalledModule only works when that PSModule was brought in through that method.

**Comment by Claudio-Merola** [comment]
The thing is that in most cases Get-Modules will not report Import-Excel module as installed when it is indeed installed and the script will fail.

We use Get-InstalledModule cause it correctly report Import-Excel module as installed every time.
