### ISSUE TITLE
Header/Footer Setup for DrawIO Output

### ISSUE THREAD

**Issue by adamdost-0** [microsoft/ARI#183]
We were looking to see if it's possible to pass in a variable or json file for customizing the Draw.IO output. If AzureResourceInventory can accept custom Header/Footer parameter file we could feed it dynamic values so that every generated file could have the values pre-generated.

**Comment by Claudio-Merola** [comment]
Hello there @adamdost-0,

Can you explain more about this? What exactly the Header/Footer parameter would change in the final diagram?

**Comment by adamdost-0** [comment]
Hey Claudio,

In the Draw.IO output this would force some form of pre-defined text to help someone understand what the diagram is for as part of an artifact they review.

* Title of the Diagram
* Timestamp
* Information Level (Contractor Proprietary, MIT Licensed etc..)
