### ISSUE TITLE
Getting an error when executing this xml file for diagram 

### ISSUE THREAD

**Issue by sver1048** [microsoft/ARI#184]
In the diagram xml file with edge, google chrome, firefox getting below error:
This XML file does not appear to have any style information associated with it. The document tree is shown below.

Also tried with io.draw & visio unable to open this file 
Inventory xml generated without any issues, only issue is with the network diagram file, tried with different syntax but getting same erorr.

Can anybody suggest solution for this ??

**Comment by Claudio-Merola** [comment]
Hello there @sver1048 

You need to open the xml file in the draw.io site (https://app.diagrams.net/). In "File" > "Open from" > "Device..."

![image](https://github.com/microsoft/ARI/assets/108147804/658c69de-dbc7-49a8-939c-2a6f8d1d5694)

**Comment by Claudio-Merola** [comment]
close due to inactivity
