### ISSUE TITLE
Report - Overview tab mostly blank - "pivottable report can't overlap a table"

### ISSUE THREAD

**Issue by psilantropy** [microsoft/ARI#185]
Hi team,

Testing this out the other day and getting good diagrams (all subs and resources look like they are there), but can't seem to get the report to generate enough data to work correctly.

After opening xlsx I get this error.

![report1](https://github.com/microsoft/ARI/assets/79955883/01bcef27-2a36-4bf1-852a-f4038bb7cde8)

When I click OK, the same error pops again. OK again and then the report shuffles a little and produces this;

![report2](https://github.com/microsoft/ARI/assets/79955883/95d209a9-36d2-4a67-9488-948a1d1cb3fb)

I get the Overview, Advisory, Policy, Subscriptions tabs.
Advisory and policy are populated with data, but subscription is blank.

Similar results with -Online -SkipDiagram --SkipAdvisor (just drops the one sheet).

Thanks 👍

**Comment by psilantropy** [comment]
Version: 3.1.14

**Comment by Claudio-Merola** [comment]
Hello there @psilantropy 

Apparently something went wrong during the script execution, 19 seconds for the extraction seems too little.

Can you run the script again using the -Debug parameter so we can see if there are any issues reported?

Thanks

**Comment by psilantropy** [comment]
Hi @Claudio-Merola, appreciate the response :)
Debug helped a lot thank you. 

Looks like I had a couple of issues with the **az account** extension.
az extension list-available --output table showed installed yesterday, but something must have happened with it. Installed ok again.


Remaining issue is here against all the resource jobs;

```
The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again. 
    + CategoryInfo          : NotImplemented: (:) [Invoke-WebRequest], NotSupportedException
    + FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
    + PSComputerName        : localhost
 
Cannot bind argument to parameter 'InputObject' because it is null.
    + CategoryInfo          : InvalidData: (:) [ConvertFrom-Json], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
    + PSComputerName        : localhost
```

**Comment by Claudio-Merola** [comment]
Hello there @psilantropy 

That's a new one. Can you post the Debug message before that error occurred?

Thanks

**Comment by psilantropy** [comment]
Fixed. User error sorry.

Somehow I ended up with C:\AzureResourceInventory\AzureResourceInventory.ps1 with C:\AzureResourceInventory\ARI-main
Moved ps1 into ARI-Main to resolve.

Debug log showed it couldn't find the subscription script.

Thanks for your time 👍
