### ISSUE TITLE
I would like to add azure inventory Services Azure Database for PostgreSQL flexible servers.

### ISSUE THREAD

**Issue by Weerayug** [microsoft/ARI#186]
I would like to add azure inventory Services Azure Database for PostgreSQL flexible servers.

**Comment by Claudio-Merola** [comment]
Hello there @Weerayug 

I just created the PostgreSQL Flexible Server module. 

Can you test the script now and see if it works?

Thanks

**Comment by Weerayug** [comment]
Hello K. @Claudio-Merola 

Tested PostgreSQL Flexible Server module and nothing happened.

thank you very much

**Comment by Claudio-Merola** [comment]
Hello @Weerayug,

Nothing happened? It didn't work?

Did you cloned the repo and tried that latest version of the main script?

**Comment by Weerayug** [comment]
Hello @Claudio-Merola 

I'm sorry for the late reply.


Thanks, I tested it and it works great.

thank you very much

**Comment by Weerayug** [comment]
thank you very much
