### ISSUE TITLE
Unused Resource or Orphange Resouce details.

### ISSUE THREAD

**Issue by BasudevWB** [microsoft/ARI#191]
Hi,
Currenlty we are filter to get the unused resourcese. Need another worksheet with all unused resource details to reduce the cost. i.e - unattaced disk, Nic, NSG, Public IP, Vnet, unused VM backup but actual VM is deleted, unused DB etc.

**Comment by albert-widjaja** [comment]
Hi @BasudevWB ,
Have you tried this module: https://github.com/itoleck/AzureSaveMoney instead?
