### ISSUE TITLE
Error running ARI

### ISSUE THREAD

**Issue by eriwol** [microsoft/ARI#192]
Hi,
Updated to v 3.1.16 and start having problems. First few runs opened Edge browser for sign-in, then errors with: "code": "ResponsePayLoadTooLarge"

Next attempts of running ARI doesn't open Edge but a non-responsive login box. 

Any ideas what's wrong? or something I should update?

**Comment by Claudio-Merola** [comment]
Hi @eriwol 

that's odd, can you run the script adding the -Debug parameter and posting the output messages before and after the error?

Thanks

**Comment by eriwol** [comment]
Hi, thank you:
This worked flawlessly until today, perhaps updating some modules caused this? I will also try running the script from another server today if I get the time.
![image](https://github.com/microsoft/ARI/assets/79441992/31fbd122-f6c2-459a-84b3-629887582208)

![image](https://github.com/microsoft/ARI/assets/79441992/c928d76b-2af8-4648-b716-149eca0e11be)

![image](https://github.com/microsoft/ARI/assets/79441992/b448630b-0b71-42b8-b252-bbc17f85ed1a)

Finishes with login box open wihich is unresponsive:
![image](https://github.com/microsoft/ARI/assets/79441992/97c9df25-89b7-4414-bb3f-aa37a77b17c2)

**Comment by Claudio-Merola** [comment]
Hi @eriwol 

That's interesting. What parameters are you using? -IncludeTags or -ResourceGroups?

Did you download the full repository or just the main script?

Thanks

**Comment by eriwol** [comment]
Hi,
Just the main script with these parameters:
.\AzureResourceInventory.ps1 -TenantID xxxxxx -Online -ReportDir "C:\AzureResourceInventory-report\NCA" -SecurityCenter -DiagramFullEnvironment -IncludeTags

Tried a new setup on a new server 2022 with same behaviour:
First run:
![image](https://github.com/microsoft/ARI/assets/79441992/9b15cf2e-5c40-4308-bcf3-faf64fc3cffe)

Second run:
![image](https://github.com/microsoft/ARI/assets/79441992/fc8f0c69-9f5c-413c-8bcd-312bc7095387)

Could it be some az cli modules has channged or is it my setup?

**Comment by sbirdi** [comment]
I'm experiencing the same error message with it prompting with `az login` and pops up with a dialog window to select the relevant Azure account to use, it then hangs at this point.
It seems to work by authenticating with the `-DeviceLogin` option.

**Comment by Claudio-Merola** [comment]
Hi @eriwol 

az cli changed the way it authenticate (by providing a pop-up windows)

I have updated the az cli to be in the exact same version you have, but I'm not having this issue:

![image](https://github.com/microsoft/ARI/assets/108147804/66716973-85ad-4a34-8048-4b6ad1d7baa2)

I have also used the exact same parameters.

One thing I noticed is that your authentication prompt does not have the accounts cached:

![image](https://github.com/microsoft/ARI/assets/108147804/40129224-f94b-47bf-b405-1e41c2e5c791)

As @sbirdi mentioned, can you try using the -DeviceAuthentication ?

**Comment by eriwol** [comment]
Should this be on the commandline like this or in the ARI script itself? Tried the below but with same error.
.\AzureResourceInventory.ps1 -TenantID xxxxx -DeviceAuthentication -Online -ReportDir "C:\AzureResourceInventory-report" -Diagram -IncludeTags

![image](https://github.com/microsoft/ARI/assets/79441992/2fc2aa7e-1352-44fb-bb11-d71a230187d1)

**Comment by Claudio-Merola** [comment]
@eriwol 

Its a parameter: "-DeviceLogin"

run like that:

.\AzureResourceInventory.ps1 -TenantID xxxxx -DeviceLogin -Online -ReportDir "C:\AzureResourceInventory-report" -Diagram -IncludeTags

It will ask you to authenticate in a different manner.

**Comment by eriwol** [comment]
See above, that's what I tried 😊, made no difference for me.

**Comment by Claudio-Merola** [comment]
but you write "-DeviceAuthentication" in the command line not "-DeviceLogin" 😄

**Comment by eriwol** [comment]
Oh no sorry, how did I manage that?, 🙃 Will try again with the correct parameter this time (and clean my glasses)

**Comment by eriwol** [comment]
Worked perfectly! Keep up the good work, this is an awesome tool 😊
