### ISSUE TITLE
-SubscriptionID parameter is not used 

### ISSUE THREAD

**Issue by demirag** [microsoft/ARI#196]
I am using the version 3.1.17.

It seems like passing SubscriptionID parameter has no affect. I still get report for all 17 subscriptions I have.

**Comment by demirag** [comment]
Hello @Claudio-Merola 

I use cloudshell and use the following command:

`./AzureResourceInventory.ps1 -TenantId xxxx-xxxx-xxxxx-xxxxxx -SubscriptionID xxxxx-xxxxxx-xxxx-xxxxx -Debug`

This creates report for all subscriptions not just one.

**Comment by Claudio-Merola** [comment]
Hello @demirag 

You were right, there was a bug when using Cloudshell.

I just submitted a version 3.1.18 that should fix that.

Can you try that version and let me know if it works correctly?

Thanks

**Comment by demirag** [comment]
@Claudio-Merola Thank you. I can confirm now it works as expected.
