### ISSUE TITLE
Subscription filter only applies partially

### ISSUE THREAD

**Issue by JanKnipp** [microsoft/ARI#197]
Hi, 
i'm using version: 3.1.24 and it seems that the subscription filter does not fully apply in the Powershell Desktop version (have not tested cloud shell yet).

It will show data from multiple subscriptions although the tab "Subscription" is then only filled for the specified subscription, but the other tabs still show the data (of the other subs) so it seems that it still collects the data and inputs it into the table.
The same applies to the charts generated in draw.io - for the request subscription in contains a tab with the subscription name and then there are also multiple "unknown" tabs with the other subscriptions.

Based on the stats that ARI outputs the amount of resources, advisories & policies is also identical when i remove the subscriptionfilter completly - the runtime is also almost identical.
The file with no filter will contain the "same" data, except that the "Subscription" column on each tab is now filled with the appropriate subscription.

Regards,
Jan

**Comment by Claudio-Merola** [comment]
Hello @JanKnipp 

You are right. There was a bug in one of the functions responsible for extracting resources from Azure.

I just fixed it with version **3.1.25**, can you try that version and tell me if worked?

Thanks

**Comment by JanKnipp** [comment]
Thanks @Claudio-Merola,
it seems to be working fine now.

Regards,
Jan
