### ISSUE TITLE
Azure IPv4/IPv6 subnet prefixes are not displayed in report

### ISSUE THREAD

**Issue by jimparker96** [microsoft/ARI#203]
AzureResourceInventory version 3.1.38

Within the excel report, "Virtual Networks" tab, when an Azure subnet has been configured as dual-stack IPv4 and IPv6, the "Subnet Prefix" column does not display the prefixes, instead the cell contains "System.Collections.ArrayList"

**Comment by Claudio-Merola** [comment]
Hello @jimparker96 

I believe I have that fixed, but I will release it with the new version of the script that is almost ready.
