### ISSUE TITLE
Report does not contain Azure Firewall information / tab

### ISSUE THREAD

**Issue by jimparker96** [microsoft/ARI#205]
AzureResourceInventory version 3.1.38

I see there is a module for Azure Firewall but when running the report, no firewall information is being displayed in the report

Just using a standard SKU azure firewall for testing

**Comment by Claudio-Merola** [comment]
Hello @jimparker96 

That's odd, can you validate if the number of resources for the other resources is correct for the environment? like the number of Load Balancers, VMs, etc

**Comment by Manish-Bharathi** [comment]
Even I'm facing the same issue, i have a subscription with 4 firewalls but none getting listed in the report.

**Comment by Claudio-Merola** [comment]
Hello @Manish-Bharathi 

Do the firewalls have Rule Collections? Network Rules?

**Comment by Manish-Bharathi** [comment]
Hi @Claudio-Merola ,

Yes, the firewall have Rule Collections

**Comment by Claudio-Merola** [comment]
Hello @Manish-Bharathi 

Can you update the module to 3.5.3 and see if this was fixed?
