### ISSUE TITLE
Please also update (or delete) the HowTo

### ISSUE THREAD

**Issue by mplogas** [microsoft/ARI#213]
The [HowTo ](https://github.com/microsoft/ARI/blob/main/HowTo.md) still assumes there is a ps1 file to execute. Wit the latest release you switched to PSM (modules) and the documentation misses the step how to import and execute the module . 
 
`Import-Module .\AzureResourceInventory.psm1`
`Invoke-ARI`

**Comment by Claudio-Merola** [comment]
@mplogas 

you are absolutely right, I forgot to update it.

Should be good now.

Thanks for the heads-up
