### ISSUE TITLE
ManagementGroup option is not working

### ISSUE THREAD

**Issue by fepere** [microsoft/ARI#218]
Hello @Claudio-Merola 
I'm trying to split the ARI between managementgroups to reduce the time to collect and processing the data.

But the option -managementGroup is not working, I sent the -TenantID -managementGroup options and after I connect to Azure using my credential or SPN the ARI 3.5.2. closed the powershell.

Please review the

**Comment by SneakPeak2003** [comment]
maybe this will help
https://bit.ly/4evXrQ6

you may need to install the c compiler

**Comment by Claudio-Merola** [comment]
Hello @fepere 

You are right, there was a bug in there, I just updated the module to version 3.5.3 and this should be fixed, can you try it?

**Comment by mark4409** [comment]
Presumably I would use this latest version by using the -Online switch? If so then I can confirm that it's still ignoring the -ManagementGroup option for me

**Comment by Claudio-Merola** [comment]
@mark4409, No, you need to update the powershell module

The -Online switch does not work anymore.
