### ISSUE TITLE
Missing support for Azure China (21 Vianet)

### ISSUE THREAD

**Issue by red-erik** [microsoft/ARI#219]
Hello,
on previous versions we used 
-AzureEnvironment "AzureChinaCloud"

but now, Invoke-ARI does not accept it anymore

Invoke-ARI : Cannot validate argument on parameter 'AzureEnvironment'. The argument "AzureChinaCloud" does not belong to the set "AzureCloud,AzureUSGovernment" specified by the ValidateSet attribute. Supply an argument that is in
the set and then try the command again.

Regards,
Red.

**Comment by Claudio-Merola** [comment]
Hello @red-erik 

You are right, I just added the support for the environment "AzureChinaCloud" in the version 3.5.4

Can you update the powershell module and try again?

**Comment by red-erik** [comment]
Hello,
the module is accepting the parameter but it's returning a lot of errors

Update-Module : A parameter cannot be found that matches parameter name 'AcceptLicense'.
At C:\Program Files\WindowsPowerShell\Modules\AzureResourceInventory\3.5.4\AzureResourceInventory.psm1:177 char:60
+ ...             Update-Module -Name AzureResourceInventory -AcceptLicense

    + CategoryInfo          : InvalidArgument: (:) [Update-Module], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Update-Module



DEBUG: 2024-10-01_08_29_45 - Invoking Inventory Loop for AVD Resources
Search-AzGraph : {
  "error": {
    "code": "BadRequest",
    "message": "Please provide below info when asking for support: timestamp = 2024-10-01T08:29:45.8242902Z, correlationId = fce7f36e-5aa3-48e6-a730-71621bbaccda.",
    "details": [
      {
        "code": "DisallowedLogicalTableName",
        "message": "Table desktopvirtualizationresources is invalid, unsupported or disallowed."
      }
    ]
  }
}
At C:\Program Files\WindowsPowerShell\Modules\AzureResourceInventory\3.5.4\Modules\Core\ARIInventoryLoop.psm1:71 char:36
+ ... eryResult = Search-AzGraph -Query $GraphQuery -first 1000 -Subscripti ...

    + CategoryInfo          : CloseError: (:) [Search-AzGraph], ErrorResponseException
    + FullyQualifiedErrorId : BadRequest,Microsoft.Azure.Commands.ResourceGraph.Cmdlets.SearchAzureRmGraph



DEBUG: 8:29:46 AM - GetAzureRmAccessTokenCommand end processing.
ConvertFrom-SecureString : A parameter cannot be found that matches parameter name 'AsPlainText'.
At C:\Program Files\WindowsPowerShell\Modules\AzureResourceInventory\3.5.4\Modules\Inventory\ARIAPIInv.psm1:17 char:58
+     $TokenData = $Token.Token | ConvertFrom-SecureString -AsPlainText

    + CategoryInfo          : InvalidArgument: (:) [ConvertFrom-SecureString], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.ConvertFromSecureStringCommand



DEBUG: 2024-10-01_08_32_14 - Checking if Should Generate Policy Sheet.
get-job : The command cannot find the job because the job name Policy was not found. Verify the value of the Name parameter, and then try the command again.
At C:\Program Files\WindowsPowerShell\Modules\AzureResourceInventory\3.5.4\Modules\Core\ARIExtraJobs.psm1:261 char:12
+         if(get-job -Name 'Policy')

    + CategoryInfo          : ObjectNotFound: (Policy:String) [Get-Job], PSArgumentException
    + FullyQualifiedErrorId : JobWithSpecifiedNameNotFound,Microsoft.PowerShell.Commands.GetJobCommand



DEBUG: 2024-10-01_08_33_15 - Validating if Excel is installed (Extra Customizations).
New-Object : Retrieving the COM class factory for component with CLSID {00000000-0000-0000-0000-000000000000} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154
(REGDB_E_CLASSNOTREG)).
At C:\Program Files\WindowsPowerShell\Modules\AzureResourceInventory\3.5.4\Modules\Extras\ARIReportCharts.psm1:934 char:28
+             $application = New-Object -ComObject Excel.Application

    + CategoryInfo          : ResourceUnavailable: (:) [New-Object], COMException
    + FullyQualifiedErrorId : NoCOMClassIdentified,Microsoft.PowerShell.Commands.NewObjectCommand

Regards,
Red.

**Comment by Claudio-Merola** [comment]
Hi @red-erik 

there is some weird stuff going on there.

Are you using SPN? 

Are you using Automation?

Can you try to uninstall the module and install it again?

**Comment by red-erik** [comment]
Hello,
tested removing and reinstalling, with, more or less, the same result.

Regards,
Red.

**Comment by Claudio-Merola** [comment]
Hello @red-erik 

I think that should be fine, I believe that Azure Environment does not have AVD, and because of that, the Graph Table (desktopvirtualizationresources) does not exist there

**Comment by red-erik** [comment]
Thank you very much for clarifying this topic.
Everything else is working as expected.

Regards,
Red.
