### ISSUE TITLE
Numerous errors when ran from Automation Account

### ISSUE THREAD

**Issue by mark4409** [microsoft/ARI#220]
Ran from automation account following your instructions. Resulting excel file was mostly OK except for first worksheet where most charts were missing. Many errors occuring in log which I've attached.

[JobOutput_5e1c21e1-9f05-4122-9cff-407677e28692.txt](https://github.com/user-attachments/files/17121117/JobOutput_5e1c21e1-9f05-4122-9cff-407677e28692.txt)

**Comment by fredericdivita** [comment]
Hi, same, problem and error here with automation account.
[JobOutput_d43e92d6-a196-402e-b31d-0c6919effd71.txt](https://github.com/user-attachments/files/17129923/JobOutput_d43e92d6-a196-402e-b31d-0c6919effd71.txt)

**Comment by Claudio-Merola** [comment]
Hi @mark4409 @fredericdivita 

I believe you also need to use the parameter "-SkipAPIs" in the runbook

Can you test it and let me know how it goes?

**Comment by fredericdivita** [comment]
Hi @Claudio-Merola and thanks for your answer. 
Unfortunately still the same results, many errors in the execution of the script and incomplete report.
Thanks for your help

**Comment by Claudio-Merola** [comment]
Hi @fredericdivita 

but most of the errors in the previous log you sent were caused by API calls, using the -SkipAPIs will not make those API calls.

What other errors are you getting?
