### ISSUE TITLE
How to pass multiple Subscription IDs

### ISSUE THREAD

**Issue by mark4409** [microsoft/ARI#221]
Whilst the ManagementGroup option isn't working. I thought it might be an idea to pass multiple subscription IDs as your instructions imply that this is possible. Could you advise how this is done? Do they need to be comma separated? Space separated? Or something else?

**Comment by Claudio-Merola** [comment]
Hello @mark4409 

I believe the correct form is:

-SubscriptionID "00000000-0000-0000-0000-000000000000","11111111-1111-1111-1111-111111111111"
