### ISSUE TITLE
xml report (Drawio) does not work in Azure Runbook (automation)

### ISSUE THREAD

**Issue by shrekars** [microsoft/ARI#222]
I have the .xlsx report but not the xml for drawio when I execute the module from Azure Runbook.

**Comment by Claudio-Merola** [comment]
Hi @shrekars 

Azure Automation does not support the powershell commands required to build the xml file. that is why we don't support it in ARI.

Is possible that using Hybrid Worker Groups it might work, but we haven't tested that out yet.

**Comment by shrekars** [comment]
Thanks @Claudio-Merola. I will use an Azure Pipeline.
