### ISSUE TITLE
Automation error

### ISSUE THREAD

**Issue by lauroramos-pyt** [microsoft/ARI#223]
[JobOutput_e1778b37-8c6f-4be0-aafb-0a1e9b4b34f9.txt](https://github.com/user-attachments/files/17248268/JobOutput_e1778b37-8c6f-4be0-aafb-0a1e9b4b34f9.txt)

I've followed the guide for Automation but im running into issues, it does not generate any file at all in the storage account/container

command line: Invoke-ARI -TenantID 'xxxxxxxx' -SkipDiagram -SkipAPIs -Automation -StorageAccount 'storageaccprd' -StorageContainer 'azure-ARI'

The service account has reader permission in the management group.

**Comment by lauroramos-pyt** [comment]
![image](https://github.com/user-attachments/assets/c947fd08-7e62-4eea-b607-4f06b51fe285)

Tried importing module "PowershellGet" but the issue is the same

**Comment by Claudio-Merola** [comment]
Hello @lauroramos-pyt 

I believe it is fixed now on version 3.5.5. Can you try it?
