### ISSUE TITLE
Version 3.5.4 terminates when using "-Help" option

### ISSUE THREAD

**Issue by AndreasSemmelmann** [microsoft/ARI#226]
On Windows 11 (24H2) and PowerShell v7..4.5 the module terminates if you are trying to use the "-help" option. 
If you invoke this: "invoke-ari -help" the output is shown shortly and then the PowerShell console terminates.

**Comment by Claudio-Merola** [comment]
Hello @AndreasSemmelmann 

your right. There was a bug there

I believe it is fixed now on version 3.5.5. Can you try it?

**Comment by AndreasSemmelmann** [comment]
Hi @Claudio-Merola 

Thanks for the quick update. Now it works. Also thanks for this awesome tool. I will now use it more often and I will further advertise this. May bad thing is, that I have no developer background so I am not able to directly contribute to the tool. I have a few thoughts to further use/build on top of your solution. Maybe I will contact you directly via Teams if you are Ok with this?

**Comment by Claudio-Merola** [comment]
Hi @AndreasSemmelmann 

Glad it worked. 

Sure, no problem.
