### ISSUE TITLE
Automation account errors

### ISSUE THREAD

**Issue by Lordfox07** [microsoft/ARI#229]
Am I missing or need to configuration anything else when running from an Azure Automation account?
Thanks

Warning

Failed adding PivotTable 'P0': Cannot index into a null array.

Failed adding chart for pivotable 'P0': Cannot bind argument to parameter 'PivotTable' bec

Failed adding PivotTable 'P4': Cannot index into a null array.

Failed adding chart for pivotable 'P4': Cannot bind argument to parameter 'PivotTable' because it is null.

**Comment by Claudio-Merola** [comment]
Hello, the Excel file is being created?

All the required permissions were added?

All the required modules were installed?

Is this a large environment?
