### ISSUE TITLE
Can not get it to run

### ISSUE THREAD

**Issue by mkoenig-msft** [microsoft/ARI#233]
Trying to run this against all subscriptions in my Azure cloud environment. I can use az login to connect and see the list of subs, but beyond that nothing works.

Can not install the module
tried defining the repository and trusting it, Still does not work
Can not find the repository
get-module -listavailable does not show it in the list

**Comment by Claudio-Merola** [comment]
Hello @mkoenig-msft 

what are you getting when running "Install-Module -Name AzureResourceInventory" ?

Have you installed Powershell Core? 

https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.4#msi

I'm starting to suspect Windows Powershell cannot install the module.
