### ISSUE TITLE
Report is not generated in Storage accout

### ISSUE THREAD

**Issue by Valli495** [microsoft/ARI#234]
II followed the exact steps mentioned but am still encountering warnings.

Warning: Failed adding PivotTable 'P0': Cannot index into a null array.
Warning: Failed adding chart for pivotable 'P0': Cannot bind argument to parameter 'PivotTable' because it is null.
Warning: Failed adding PivotTable 'P2': Cannot index into a null array.
Warning: Failed adding chart for pivotable 'P2': Cannot bind argument to parameter 'PivotTable' because it is null.
Warning: Failed adding PivotTable 'P3': Cannot index into a null array.
Warning: Failed adding chart for pivotable 'P3': Cannot bind argument to parameter 'PivotTable' because it is null.
Warning: Failed adding PivotTable 'P4': Cannot index into a null array.
Warning: Failed adding chart for pivotable 'P4': Cannot bind argument to parameter 'PivotTable' because it is null.

No output is being sent to the storage account. Could someone assist me with this issue?

**Comment by Claudio-Merola** [comment]
Hello @Valli495, the Excel file is being created?

All the required permissions were added?

All the required modules were installed?

Is this a large environment?

If you run the runbook in test mode, do you see any error?
