### ISSUE TITLE
Feature Request: Add Performance Tier on the Disks Tab

### ISSUE THREAD

**Issue by tinathou972** [microsoft/ARI#239]
Hey,

Can you add the Performance Tier column after the SKU column in the disk tab?

Thank you

**Comment by Claudio-Merola** [comment]
Hello,

Sure we can!

I added that and a few more to be released with version 3.5.13 this week

**Comment by tinathou972** [comment]
Thanks a lot!

I can't wait for the release

**Comment by Claudio-Merola** [comment]
Hi @tinathou972 

Sorry about that, it was my bad, I ended up configuring the wrong property in that column. Please uninstall the version 3.5.13 and install the new version 3.5.14 and it should work fine now:

![Image](https://github.com/user-attachments/assets/2c1e5abe-a7e6-495d-ab9e-6a4ee8e0ad3a)

**Comment by tinathou972** [comment]
Hey @Claudio-Merola,

Thanks for your reply.
Cannot see the v.3.5.14.
I'm waiting and test it out when it's here.

Best regards

**Comment by Claudio-Merola** [comment]
Hi @tinathou972 

Did you were able to test it?

Thanks

**Comment by tinathou972** [comment]
Hello @Claudio-Merola,

Didn't see you update the code.
I'm testing it out and I'll give you a feedback.

Thanks

**Comment by tinathou972** [comment]
Hey @Claudio-Merola,

The performance tier column is empty for me,
Do I have to activate something on my tenant?

I launch the script with Invoke-ARI -TenantID <tenantid>
Thanks

**Comment by Claudio-Merola** [comment]
Performance Tier will only appear for HyperV Generation 2. 

The Disks in your environment are HyperV Generation 2 or 1?

**Comment by tinathou972** [comment]
Hello,

I don't know so I made a little fonction to deduce the performance tier thanks to Disks size and sku.

Thanks
