### ISSUE TITLE
Assume authenticated / skip authenticate steps

### ISSUE THREAD

**Issue by bfond82** [microsoft/ARI#241]
Can you add a parameter that when set, skips every connect-az account,  and Clear-AzContext. and just assumes that login is done in advance?

## Reason
I am using ARI in a Github workflow, and use the login to tenant before starting the Invoke-ari command, but event though I am logged inn, i still tries to authenticate. I can't use the the `-Automation` parameter because that uses Managed identity, which I'm not using in the Github workflow. So a simple parameter flag + in the code that normally starts connect-azaccount , and Clear-AzContext, skips these steps would be perfect.

**Comment by Claudio-Merola** [comment]
Hello,

This shouldn't be hard to set, but I would prefer to just validate if the current context is the same as the tenantid parameter. if this is the case, no authentication request would be necessary. 

We do similar methods on some other projects I'm involved.

**Comment by bfond82** [comment]
Sure, that will work to, would be perfect if it can be added to the ARI module.

**Comment by Claudio-Merola** [comment]
Hi @bfond82 

I just release version 3.5.15 and it should avoid the authentication steps if you are already authenticated.

Can you try it and let me know if works for you?

Thanks

**Comment by bfond82** [comment]
> Hi [@bfond82](https://github.com/bfond82)
> 
> I just release version 3.5.15 and it should avoid the authentication steps if you are already authenticated.
> 
> Can you try it and let me know if works for you?
> 
> Thanks

Hi, I can confirm, it works like a charm! Thank you for adding this, and for the very useful ARI tool

Here is a snippet of the output that indicates that it checked for already authenticated:

```pwsh
DEBUG: 07:51:50 - GetAzureRMSubscriptionCommand end processing.
Already authenticated in Tenant xxxxx-xxxxxxx-xxxxxxx-xxxxxxx
Extracting Subscriptions from Tenant xxxxx-xxxxxxx-xxxxxxx-xxxxxxx
DEBUG: 2024-12-20_07_51_50 - Checking report folder: /home/runner/work/*****/
Starting Resource Extraction..
DEBUG: 2024-12-20_07_51_50 - Starting Extractor function
DEBUG: 2024-12-20_07_51_50 - Powershell Edition: Core
DEBUG: 2024-12-20_07_51_50 - Powershell Version: 7.4.6
DEBUG: 2024-12-20_07_51_50 - Tags will be ignored
```

**Comment by Claudio-Merola** [comment]
Glad it worked! 

Thanks for using the tool. 

Any issue, feedback or feature request please let us know.

Thanks
