### ISSUE TITLE
VISIO drawing not working properly

### ISSUE THREAD

**Issue by hsmansur** [microsoft/ARI#38]
Hi.
I ran this script in 2 different tenants.
Tenant1: it had a few services/objects (only 19 resources), created excel file and drew the visio file perfectly - all services there.
Tenant2: it had 484 services/objects, created the excel file but the visio file only showed express route and 1 wan connection. Nothing else was show.
I ran it from the same Windows machine, same software versions (same as yours).
Any thoughts?

Tenant1:
![image](https://user-images.githubusercontent.com/43547235/136277843-08689e6e-72e8-443f-9d8c-e5e5d216cd17.png)

Tenant2:
![image](https://user-images.githubusercontent.com/43547235/136274434-fc0e7f0c-3d7c-4669-b930-19228efacaf5.png)

**Comment by hsmansur** [comment]
Hi guys.
Any news on this? Related to VWAN.
I still cannot have the design, only excel with details.
Thanks.

**Comment by ClaudioMerola** [comment]
Hi,

We are working in the version 2.2 of the script, we expect to have some update in this issue with the diagram.

The problem is that VWAN relays in several internal resources that are not open to be extracted by Resource Graph, so we are trying to workaround that.

**Comment by hsmansur** [comment]
> Hi,
> 
> We are working in the version 2.2 of the script, we expect to have some update in this issue with the diagram.
> 
> The problem is that VWAN relays in several internal resources that are not open to be extracted by Resource Graph, so we are trying to workaround that.

Thank you for such quick reply, Claudio.
Just want to say itis a fantastic work you guys are doing!
Rgs.,

Helder

**Comment by hsmansur** [comment]
Hey Claudio,
Just did.
The excel file was perfect, once again.
The drawing has issues.
I have 1 subscription only, 2 datacenters (east, west).
They both have hubs.
On West (DR), I have a hub, a few subnets, app gw, express route. They were all there.
On East I have a hub, p2s and s2s vpn, ExpressRoute, az Firewall, lots of subnets. But It only showed ER, P2S and S2S VPNs. It did not show Az Firewall or any of the internal subnets.
Do I need to add any specific permissions from my machine (I´m going thru powershell, internet, not connected to the remote network) to go thru Az Firewall to collect that data? Or should it be shown as well?
I am subscription owner.
Let me know so I can run some other tests.
Thank you for creating such a fantastic tool.

Rgs.,

Helder

**Comment by ClaudioMerola** [comment]
Hi, 

Can you post a picture of how the drawing for the east region was?

I was trying to figure what went wrong by analyzing the code, but seeing the image I think will be easier to understand where the error was.

Thanks

**Comment by Claudio-Merola** [comment]
Hello,

Sorry for the late reply, this one took some time. 

Can try the version 2.3 and see how it goes?

Thanks

**Comment by hsmansur** [comment]
> Hello,
> 
> Sorry for the late reply, this one took some time.
> 
> Can you try the version 2.3 and see how it goes?
> 
> Thanks

I'll download it and ask the team to run it, I don't have access to the environment anymore :(
I'll let you know.

Rgs.,
