### ISSUE TITLE
Error "BadRequest" when running the script

### ISSUE THREAD

**Issue by EtownFL** [microsoft/ARI#46]
Here is the Error I get when running the script.

GitCommitId                    7.1.5
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
182-776f-4a9c-b96e-8fdb9f46b2b3.",
        "details": [
            {
                "code": "DisallowedLogicalTableName",
                "message": "Table advisorresources is invalid, unsupported or disallowed."
            }
        ]
    }
}
 Azure Resource Inventory are collecting Security Center Advisories.
 Collecting Security Center Can increase considerably the execution time of Azure Resource Inventory and the size of final report     

ERROR: {
    "error": {
        "code": "BadRequest",
        "message": "Please provide below info when asking for support: timestamp = 2021-11-03T21:40:06.9146572Z, correlationId = bf6f0bac-dac0-49c4-ba4e-27ce82ee330f.",
        "details": [
            {
                "code": "DisallowedLogicalTableName",
                "message": "Table desktopvirtualizationresources is invalid, unsupported or disallowed."
            }
        ]
    }
}
Report Complete. Total Runtime was: 1.08 Minutes
Total Resources: 0
Total Advisories: 0
Total Security Advisories: 194

**Comment by ClaudioMerola** [comment]
Hi,

Can you run the script using the parameter "-Debug", and post the output here so we can see the details of whats going on?

Thanks
