### ISSUE TITLE
Update Automation script to the latest version

### ISSUE THREAD

**Issue by camilohtaborda** [microsoft/ARI#53]
Hello team. 

I have been an active user to this tool and I'm very happy to use it because it works very well. Currently I'm performing the automation part to save the Excel files directly in the Storage Account, but I realize the code that is in the folder Automation is for the 2.1.0 version and the latest version of the ARI script is on 2.1.10 version. I would like to know, how could I update the Automation script to get the Excel files on the latest version? It is possible to copy the AzureResourceInventory.ps1 code into the runbook and run? I've tried this but I get the Excel file without the variables (SecurityCenter, IncludeTags, etc).

Thanks for this tool.

**Comment by ClaudioMerola** [comment]
Hello,

Thanks for using the tool,

Actually there is not much difference between those 2 versions in the main script.

Even the automation script is older, it is using the newest module files in the repo. 

We are working in a bigger update in the main script (version 2.2). That update will require to change a few things in the Automation script.

Stay tune for news very soon.

Thanks

**Comment by camilohtaborda** [comment]
Thanks Claudio, I'll be waiting for the new version.
