### ISSUE TITLE
Excel File not being written

### ISSUE THREAD

**Issue by jasonwhand** [microsoft/ARI#56]
The script is running and not producing any errors and it concludes with this but there is no file in the c:\AzureResourceInventory folder:

Report Complete. Total Runtime was: .73 Minutes
Total Resources: 1327
Total Advisories: 315

Excel file saved at: C:\AzureResourceInventory\AzureResourceInventory_Report_2022-03-08_13_15.xlsx

**Comment by jasonwhand** [comment]
I added the -online parameter that I saw on another issue post and it is creating the excel file but I have Visio installed and visio plan 2 license and it isn't creating the visio file.  I am on the latest Windows 10 with all the az cli freshly installed from the latest version.  Any ideas?

**Comment by jasonwhand** [comment]
I figured out that I needed to add the -Diagram option so it is now producing the diagrams.  The -Quotausage parameter doesn't appear to do anything nor does the -appid parameter.  Thanks again for this tool.  Helps to see what is pretty difficult to see overall.  

Do you know if you will include SQL MI's in future versions?

**Comment by ClaudioMerola** [comment]
Hi Jason, sorry for the late response. 

The -QuotaUsage will add a sheet in the excel with the Quota Usage for every subscriptions.

What do you mean with SQL MI's ?

Thanks

**Comment by jasonwhand** [comment]
I was saying it would be nice if the report also showed the SQL Managed Instances in Azure.  We have several.

Thanks,
Jason

**Comment by dlsmothers** [comment]
Adding the -online parameter fixed my issue, thank you.
