### ISSUE TITLE
Add Environment Parameter for Connect-AZAccount

### ISSUE THREAD

**Issue by mrclemensiii** [microsoft/ARI#69]
Can we update this code with the Environment Parameter for Connect-AZAccount?  It could default to AzureCloud but would allow us to set it for other environments like AzureUSGovernment as well.

**Comment by Claudio-Merola** [comment]
Hi,
Thanks for the suggestion, this was added in the version 2.3.1. The parameter name is "-AzureEnvironment".

Thanks
