### ISSUE TITLE
Subscription field not populated in the Subscriptions tab

### ISSUE THREAD

**Issue by JiBo87** [microsoft/ARI#70]
In the produced Excel document the Subscription field is not populated in the Subscriptions tab

![image](https://user-images.githubusercontent.com/88667083/175475755-fdbe1022-e81f-4d97-99f0-5cdf7867c1d4.png)

in other tabs in the Excel the info is there: 
![image](https://user-images.githubusercontent.com/88667083/175475993-a5920d79-41b6-47ae-8654-19e9dbae9c60.png)

**Comment by VessyU** [comment]
> In the produced Excel document the Subscription field is not populated in the Subscriptions tab
> 
> ![image](https://user-images.githubusercontent.com/88667083/175475755-fdbe1022-e81f-4d97-99f0-5cdf7867c1d4.png)
> 
> in other tabs in the Excel the info is there: ![image](https://user-images.githubusercontent.com/88667083/175475993-a5920d79-41b6-47ae-8654-19e9dbae9c60.png)

Change the code to the following, seems to work for me

![image](https://user-images.githubusercontent.com/102477917/178968641-f4fa4814-efb4-474e-8601-ad25fa765b23.png)

**Comment by Claudio-Merola** [comment]
Hello, we rollback the script to use Azure CLI, can you try the version 2.3 and see if this issue persists?
