### ISSUE TITLE
Security Advisor Subscriptions

### ISSUE THREAD

**Issue by VessyU** [microsoft/ARI#71]
For the security advisor when enabled doesn't populate the subscription field for the entries as seen below:
![image](https://user-images.githubusercontent.com/102477917/178971763-dfe62611-ad10-49a2-a402-4ce844c612fd.png)

Was able to get it to work with the following for anyone who needs it

![image](https://user-images.githubusercontent.com/102477917/178971890-b99fd04a-5dd2-4d7a-9021-96e679f3c6a8.png)

**Comment by Claudio-Merola** [comment]
Hello, we rollback the script to use Azure CLI, can you try the version 2.3 and see if this issue persists?
