### ISSUE TITLE
Can't get subscription name in sheet "Subscriptions" after upgraded to 2.2

### ISSUE THREAD

**Issue by HuJiongYu** [microsoft/ARI#72]
![image](https://user-images.githubusercontent.com/96169480/180628544-4be21556-0c99-4199-a682-8a5f4d609cbe.png)

looks like it can't export subscription name in the last sheet "Subscriptions" after I upgrade it to 2.2, 

Thanks in advance

**Comment by Claudio-Merola** [comment]
Hello, we rollback the script to use Azure CLI, can you try the version 2.3 and see if this issue persists?

**Comment by HuJiongYu** [comment]
@Claudio-Merola 

Thanks for your quick response. will try 2.3 on this Monday, I will update the screenshot here

Thanks again
