### ISSUE TITLE
ERROR "WE FIND A PROBLEM IN A CONTENT OF "AZURERESOURCEINVENTORY_REPORT_XXXX-XX-XX-XX."

### ISSUE THREAD

**Issue by LucianoMatte** [microsoft/ARI#73]
AFTER UPGRADING THE ARI TO VERSION 2.2, WHEN GENERATING THE EXCEL FILE OCCURS THE ERROR "WE FIND A PROBLEM IN A CONTENT OF "AZURERESOURCEINVENTORY_REPORT_XXXX-XX-XX-XX." SOME GRAPHICS ARE BROKEN OR NOT GENERATED. HAVE YOU EVER HAD THIS PROBLEM?

THANKS FOR THE HELP

**Comment by Claudio-Merola** [comment]
Hello, we rollback the script to use Azure CLI, can you try the version 2.3 and see if this issue persists?
