### ISSUE TITLE
find zero resource after running .\AzureResourceInventory.ps1

### ISSUE THREAD

**Issue by zhengmaowang** [microsoft/ARI#74]
I run this script but can't get any resources, i login into my Azure, but it seems bind to wrong subscription. 
PS C:\Windows\SysWOW64\WindowsPowerShell\v1.0\ARI> .\AzureResourceInventory.ps1
Validating Az Cli..
WARNING: You have 1 updates available.

Please let us know how we are doing: https://aka.ms/azureclihats
and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
Validating Az Cli Extension..
Validating ImportExcel Module..
PowerShell Desktop Identified.

Azure Cloud Environment: AzureCloud
Tenant ID not specified. Use -TenantID parameter if you want to specify directly.
Authenticating Azure

You have privileges only in One Tenant

Extracting from Tenant xxxxxxx-xxxx-xxxx-xxxx-xxxxxxx

 To include Security Center details in the report, use <-SecurityCenter> parameter.

Report Complete. Total Runtime was: 1.08 Minutes
Total Resources: 0
Total Advisories: 0

Excel file saved at: C:\AzureResourceInventory\AzureResourceInventory_Report_2022-08-09_06_39.xlsx

**Comment by kumammanish** [comment]
Same issue. O resources in the report.

 _"Azure Resource Inventory are collecting Security Center Advisories.
 Collecting Security Center Can increase considerably the execution time of Azure Resource Inventory and the size of final report 
 
Report Complete. Total Runtime was: .94 Minutes
Total Resources: 0
Total Security Advisories: 0"_

**Comment by Claudio-Merola** [comment]
Hello, 

That's generally caused by different version of AZ CLI extension version. 

Can you try to run: "az upgrade" and see if any extension is updated?

Thanks
