### ISSUE TITLE
Azure Cost Utilization overview data

### ISSUE THREAD

**Issue by aayooshmoitro** [microsoft/ARI#75]
Hi,
First of all, thank you for this script which provides the all necessary inventory data in one excel sheet however I was wondering if you have any plans to incorporate the cost utilization report with TAG columns so that we can also know the exact cost per TAGs across all the subscription? Thank you for this script. :)

**Comment by Claudio-Merola** [comment]
Hi,

Thanks for your comment. 

We do have plans to release a parallel project named Azure Cost Inventory. But the presentation and the type of data to be presented is going to be slightly different from ARI. I believe it is going to be made available in the late Aug.

Thanks

**Comment by aayooshmoitro** [comment]
That's Great news!

Would appreciate if we can pull cost utilization using tags.

Looking forward for the cost inventory  :)

**Comment by aayooshmoitro** [comment]
Hi,
Checking back if the Azure inventory is publicly available? :) Would appreciate if you can update this thread with the link when the project is released. Thanks again.

**Comment by Claudio-Merola** [comment]
Hello,
The powershell script to make the inventory is complete for a while, in fact just need to check if it's still working as expected. 

I'm waiting for some colleges to finish the presentation part that is going to be a little different there. Hope we can get that before Oct.
