### ISSUE TITLE
Multiple Subscriptions Error

### ISSUE THREAD

**Issue by Arodriguez81** [microsoft/ARI#76]
The script is passing all subscriptions in one line. no as an array. When using one subscription works fine.

ERROR: {
    "code": "BadRequest",
    "message": "Please provide below info when asking for support: timestamp = 2022-09-09T16:37:56.8022696Z, correlationId = a056e40d-a55e-474b-acb0-f928ffcacbf7.",
    "details": [
        {
            "code": "SubscriptionsContainInvalidGuids",
            "message": "Subscription ids have to be valid GUIDs. Given: 'xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx'."

**Comment by Claudio-Merola** [comment]
Hello,

Can you check the Azure CLI version you are using? 

Thanks

**Comment by Arodriguez81** [comment]
2.40.0

**Comment by cybersh3ll** [comment]
If you specify -suscription subID works fine... the problem is only with multiple subs

**Comment by cybersh3ll** [comment]
I get it working again using AzureCLI ver. 2.39.0 
https://azcliprod.blob.core.windows.net/msi/azure-cli-2.39.0.msi

**Comment by Claudio-Merola** [comment]
That's very strange. 

I've been messing with that bug for a while now and passing the multiple subs directly in the "az graph query" is working fine. The problem is only when passing it through variables. 

Seems very bizarre how a change in the az cli could impact that. 

I'll try to work around it somehow in the next days.

**Comment by Claudio-Merola** [comment]
Hello

I believe we found a bug in az cli or resource-graph extension. Until they fix it on the az cli side we can't do much I'm afraid.

For now, I removed the parameters -SubscriptionID and -ResourceGroup.

Will keep you posted.

**Comment by KlemenDanfoss** [comment]
@Claudio-Merola can we use -SubscriptionID again in the latest versions? I'm using latest versions of both azcli and this script but it always goes through all subscriptions.
