### ISSUE TITLE
Hwo to tell difference between App Service - Function and App Service - Web Site

### ISSUE THREAD

**Issue by rodneyjoyce** [microsoft/ARI#77]
Hello,

Is it possible to distinguish between App Services that are Azure Functions and Websites (App Services)?

**Comment by Claudio-Merola** [comment]
Hello,

Yes, the column "App Type" distinguishes the type.

Unfortunately, in the Azure Resource Graph they are basically the same type of resource. That's why they are all in the same Excel Tab
