### ISSUE TITLE
No data in Advisory sheet Azure Resource Inventory v2.3

### ISSUE THREAD

**Issue by Diljithkp** [microsoft/ARI#78]
After generating the ARI report advisory sheet is blank and all other pages are listed.

**Comment by Claudio-Merola** [comment]
Hello,
I found a minor bug related to that, but it should not affect that reporting. 

Anyway, can you try the version 2.3.7 and also run the script with -Debug parameter to see if any errors occur?

Thanks

**Comment by Cyb3rK1ll** [comment]
> After generating the ARI report advisory sheet is blank and all other pages are listed.

Are you using Azure CLI 2.39.0?

**Comment by Claudio-Merola** [comment]
I believe this was caused by a bug in az cli. 

Can you try the version 2.3.8?

thanks
