### ISSUE TITLE
The number of Azure Resources is different from actual

### ISSUE THREAD

**Issue by fatwai** [microsoft/ARI#80]
I have tried below two commands to generate Azure Resource Inventory Reports.

Case 1: run ".\AzureResourceInventory.ps1 -IncludeTags -Diagram -SecurityCenter -QuotaUsage"
The size of SQL Servers is **17**.

Case 2: run ".\AzureResourceInventory.ps1 -Diagram -SecurityCenter -QuotaUsage"
The size of SQL Servers is **37**.

Case 3: run ".\AzureResourceInventory.ps1"
The size of SQL Servers is **37**.

Actually the web portal shows **33** records. 

I'm using AzureResourceInventory.ps1 version 2.3.9 and azure-cli version 2.40.0.

**Comment by Claudio-Merola** [comment]
Hello,

I suspect the 37 is because the spreadsheet contains 1 row for each Private Endpoint, and you should have SQL Servers with more than 1.

The odd part is the 17, I'm suspecting is because some SQL Servers don't have Tags perhaps?

Can you run the ".\AzureResourceInventory.ps1 -IncludeTags -Diagram -SecurityCenter -QuotaUsage" one more time just to make sure?

Thanks

**Comment by fatwai** [comment]
Hello Claudio,

After run ".\AzureResourceInventory.ps1 -IncludeTags -Diagram -SecurityCenter -QuotaUsage" once again, the size of SQL Servers is still 17.
***@***.***

And the spreadsheet of SQL Servers shows some tags are empty.
***@***.***

Actually there are 33 SQL servers in the Azure Subscription.
***@***.***

Thanks and Regards,



Kwok Wai Chan
Technical Consultant, Infrastructure Services
Eastech Systems Limited
M: (852) 60529906 |
 T: (852) 27998882 | F: (852) 27999077

**Comment by Claudio-Merola** [comment]
Hello,

I fixed one minor bug in the SQL Server module.

Can you download the files and try again using the -IncludeTags?

Thanks

**Comment by fatwai** [comment]
Hi Claudio,

After re-trial with - IncludeTags, the size of SQL Server is 37 now.
***@***.***

But that of SecurityCenter is 0:
***@***.***

It has contents of the spreadsheet:
***@***.***

Anyway, thanks for fixing the SQL Server module.

Best Regards,



Kwok Wai Chan
Technical Consultant, Infrastructure Services
Eastech Systems Limited
M: (852) 60529906 |
 T: (852) 27998882 | F: (852) 27999077
