### ISSUE TITLE
Support Virtual Wan, Virtual Hub, and NVA

### ISSUE THREAD

**Issue by coolhome** [microsoft/ARI#87]
Currently missing an entire ecosystem of Virtual WAN, Virtual Hubs, and NVAs. It does show the peering from vnet to hub but nothing else.

I think this is a bug and feature request I believe.
```ps1
DEBUG: Running Module: 'C:\...\ARI\Modules\Networking\VirtualWAN.ps1'
$Resources contains the VirtualWans
$SmaResources empty VirtualWAN
```

The bug is the VirtualWan.ps1 module never generated an excel tab.
The feature being able to draw VWAN Hub-Spoke diagram
The feature of seeing NVA in excel tab.

**Comment by coolhome** [comment]
I tried to debug this and I discovered running with and without `-Online` produces different results with the same credentials. I think there may be a bigger bug here.

Offline:
```
DEBUG: Jobs Compleated.
DEBUG: Job ResourceJob_1 Returned: 27 Resource Types.
DEBUG: Starting Reporting Phase.
DEBUG: Running Offline, Gathering List Of Modules.
```

Online:
```
DEBUG: Jobs Compleated.
DEBUG: Job ResourceJob_1 Returned: 62 Resource Types.
DEBUG: Job ResourceJob_1 Returned: 0 Resource Types.
DEBUG: Starting Reporting Phase.
```

**Comment by cveld** [comment]
I am specifically looking for a script to export the IP plan of a virtual wan topology. Not sure if ARI is the right fit after fixing OP's request.

**Comment by Claudio-Merola** [comment]
Hello,

Just to inform that we are still investigating this issue

**Comment by Claudio-Merola** [comment]
Hello,

Can you try the version 2.3.11 and see how it goes?

Thanks

**Comment by coolhome** [comment]
@Claudio-Merola using the latest version I know see the Virtual WAN. Does not seem to be polling any NVAs tho. 

For the chart, we have both Virtual WAN and the non Virtual WAN approach. The diagram only shows one, but I think I might be an edge case.
