### ISSUE TITLE
Not all region or resource is shown in the graph

### ISSUE THREAD

**Issue by cheeleonglow** [microsoft/ARI#88]
Hi Author,

the PowerShell  script works great and I been able to generate some good diagram with it using Draw.io.

I noticed there are some resources not able to generated in the diagram, however it is shown inside the excel inventory list.

Some of the items i noticed so far is the vnet, region resources and also MySql databases.

Is this expected or some tech issues?

Hope to hear from you soon,

Thanks and regards,
Low

**Comment by Claudio-Merola** [comment]
Hello,

This is kind of expected. 

The network topology will only draw the virtual networks that are connected through the OnPrem environment. 

But is possible to draw the whole topology (all virtual networks, even the ones not peered). for that you must edit the file: **./Extras/DrawIODiagram.ps1** at line **29** you must change:
**From:** "$Global:FullEnvironment = $false" 
**to:** "$Global:FullEnvironment = $true"

:)

**Comment by cheeleonglow** [comment]
Hi Claudio,

thanks for the comment. I will give it a try and revert!

Thanks and regards,
Low

**Comment by cheeleonglow** [comment]
Hi Claudio,

I downloaded the DrawIODiagram.ps1 and edited accordingly.

I edit within the AzureResourceInventory.ps1 where i find the calling for DrawIODiagram.ps1, shown as below

            Start-job -Name 'DrawDiagram' -ScriptBlock {

                If ($($args[5]) -eq $true) {
                    $ModuSeq = (New-Object System.Net.WebClient).DownloadString($($args[7]) + 'C:\Users\LowCheeLeong\OneDrive\Desktop\ARI\DrawIODiagram.ps1')
                }
                Else {
                    $ModuSeq0 = New-Object System.IO.StreamReader($($args[0]) + 'C:\Users\LowCheeLeong\OneDrive\Desktop\ARI\DrawIODiagram.ps1')
                    $ModuSeq = $ModuSeq0.ReadToEnd()
                    $ModuSeq0.Dispose()  

is there any where i doing it wrongly?

Hope to hear from you soon!

**Comment by Claudio-Merola** [comment]
Hello,

Actually, you didn't need to edit the AzureResourceInventory.ps1. 

Just download the whole repo and edit the DrawIODiagram.ps1 locally. 

If you run the AzureResourceInventory.ps1 without any parameters, it will use the local files, in your case, the DrawIODiagram you edited.

**Comment by cheeleonglow** [comment]
Finally gotten the things i wanted! Many thanks!
