### ISSUE TITLE
Cost Utilization data - ref #75

### ISSUE THREAD

**Issue by danilansible** [microsoft/ARI#95]
Hi ,

Is the Azure Cost Inventory effort discontinued, Could not locate the repo of that project in github. 
Is there an alternate to get an overview of costs for all subscriptions.
Ref : #75

**Comment by Claudio-Merola** [comment]
Hi,

Yea, we had a few issues with the project, but is not dead yet. 

We are working to get it release as soon as possible, but it might still take some time :(
