### ISSUE TITLE
Diagram is empty

### ISSUE THREAD

**Issue by aloizeau** [microsoft/ARI#96]
Hi Claudio & Renato,
I test the script today using the version [2.3.15](https://github.com/microsoft/ARI/commit/505d434a4b8d013a6a96874c7cf037c5ce4705e6) on a resource group with many PaaS services and I don't have any services on the final XML file.

I've got only this XML content:
> `<mxfile host="Electron" modified="2021-10-01T21:45:40.561Z" agent="5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) draw.io/15.4.0 Chrome/91.0.4472.164 Electron/13.5.0 Safari/537.36" etag="wtrsJfUcdQuyKhaIZTOi" version="15.4.0" type="device">
> <diagram id="gUpzJqDmcASiFZnshYfX" name="Page-1">
> <mxGraphModel dx="1326" dy="798" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="850" pageHeight="1100" math="0" shadow="0">
> <root>
> <mxCell id="0"/>
> <mxCell id="1" parent="0"/>
> <object label="" id="VHLXzbCrEFKZcBslhyiO-0">
> <mxCell style="rounded=0;whiteSpace=wrap;fontSize=16;html=1;sketch=0;fontFamily=Helvetica;" vertex="1" parent="1">
> <mxGeometry x="-520" y="-100" width="500" height="102" as="geometry"/>
> </mxCell>
> </object>
> <object label="Cloud Only Environment" id="VHLXzbCrEFKZcBslhyiO-1">
> <mxCell style="aspect=fixed;html=1;points=[];align=center;image;fontSize=56;image=img/lib/azure2/compute/Cloud_Services_Classic.svg;" vertex="1" parent="1">
> <mxGeometry x="-460" y="51" width="380" height="275" as="geometry"/>
> </mxCell>
> </object>
> <object label="Powered by: Azure Resource Inventory v2.3 https://github.com/microsoft/ARI" author1="Claudio Merola" author2="Renato Gregio" id="VHLXzbCrEFKZcBslhyiO-2">
> <mxCell style="aspect=fixed;html=1;points=[];align=left;image;fontSize=22;image=img/lib/azure2/general/Dev_Console.svg;" vertex="1" parent="1">
> <mxGeometry x="-520" y="102" width="27.5" height="22" as="geometry"/>
> </mxCell>
> </object>
> </root>
> </mxGraphModel>
> </diagram>
> </mxfile>`

Here you can see the command that I used to make the inventory:
![2023-01-05_15-12-10](https://user-images.githubusercontent.com/13063338/210800996-7c7e6d8f-6628-4da1-8c99-3540d0f71114.png)

I used the script on **Windows 11** with 

- az cli in 2.43.0 
- PowerShell in 7.2.8
- resource-graph in 2.1.0
- Python (Windows) in 3.10.8

**Comment by aloizeau** [comment]
I add the '**-Debug**' option but I not see any errors:

❯ .\AzureResourceInventory.ps1 -TenantID xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx -IncludeTags -Diagram -SecurityCenter -QuotaUsage -SubscriptionID xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx -ResourceGroup myApp-int-fc -ReportName myApp -ReportDir d:\Temp\myApp -Debug
DEBUG: Debbuging Mode: On. ErrorActionPreference was set to "Continue", every error will be presented.
DEBUG: Cleaning default variables
DEBUG: Starting Extractor function
DEBUG: Starting Extractor function
DEBUG: Starting checkAzCli function
Validating Az Cli..
DEBUG: Current az cli version: azure-cli                         2.43.0
Validating Az Cli Extension..
DEBUG: Current Resource-Graph Extension Version: 2.1.0
Validating ImportExcel Module..
DEBUG: ImportExcel Module Version: ..
DEBUG: Starting checkPS function
PowerShell Desktop Identified.

DEBUG: Starting LoginSession function
Azure Cloud Environment: AzureCloud
DEBUG: Tags will be included
DEBUG: Number of Subscriptions Found: 1
DEBUG: Checking report folder: d:\Temp\myApp\
DEBUG: Extracting Resources from Subscription: 9339de36-fa74-4ef4-ae70-39f3192c9388. And from Resource Group: myApp-int-fc
DEBUG: Subscriptions To be Gather in Advisories: 1
DEBUG: Advisories: 1
 Azure Resource Inventory are collecting Security Center Advisories.
 Collecting Security Center Can increase considerably the execution time of Azure Resource Inventory and the size of final report

DEBUG: Extracting total number of Security Advisories from Tenant
DEBUG: Excel file:d:\Temp\myApp\myApp_Report_2023-01-05_15_41.xlsx
DEBUG: Excel Table Style used: Light20
DEBUG: Importing List of Unsupported Versions.
DEBUG: Looking for the following file: D:\Download\ARI-main\Extras\Support.json
DEBUG: Checking if Draw.io Diagram Job Should be Run.
DEBUG: Starting Draw.io Diagram Processing Job.
DEBUG: Checking If Should Run Security Center Job.
DEBUG: Starting Security Job.
DEBUG: Checking If Should Run Advisory Job.
DEBUG: Starting Advisory Processing Job.
DEBUG: Starting Subscriptions job.
DEBUG: Starting Processing Jobs.
DEBUG: Starting Jobs Collector.
DEBUG: Jobs Still Running: 1
DEBUG: Jobs Compleated.
DEBUG: Job ResourceJob_1 Returned: 7 Resource Types.
DEBUG: Starting Reporting Phase.
DEBUG: Running Offline, Gathering List Of Modules.
DEBUG: Modules Found: 53
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Analytics\Databricks.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Analytics\EvtHub.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Analytics\Streamanalytics.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Analytics\WrkSpace.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Compute\APPSERVICEPLAN.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Compute\APPSERVICES.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Compute\ARCServers.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Compute\ARO.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Compute\AVD.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Compute\CloudServices.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Compute\IoT.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Compute\VM.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Containers\AKS.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Containers\CONTAINER.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Containers\REGISTRIES.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Containers\VMSS.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Data\CosmosDB.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Data\MariaDB.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Data\MySQL.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Data\POSTGRE.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Data\RedisCache.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Data\SQLDB.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Data\SQLMI.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Data\SQLMIDB.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Data\SQLSERVER.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Data\SQLVM.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Infrastructure\AppGW.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Infrastructure\AutomationAcc.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Infrastructure\AvSet.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Infrastructure\BASTION.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Infrastructure\Frontdoor.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Infrastructure\RecoveryVault.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Infrastructure\Vault.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Integration\APIM.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Integration\ServiceBUS.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Networking\AzureFirewall.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Networking\Connections.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Networking\ExpressRoute.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Networking\LoadBalancer.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Networking\NATGAteway.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Networking\NetworkSecurityGroup.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Networking\PrivateDNS.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Networking\PublicDNS.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Networking\PublicIP.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Networking\ROUTETABLE.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Networking\TrafficManager.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Networking\VirtualNetwork.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Networking\VirtualWAN.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Networking\VNETGTW.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Networking\vNETPeering.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Storage\DataExplorerCluster.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Storage\StorageAcc.ps1'
DEBUG: Running Module: 'D:\Download\ARI-main\Modules\Storage\VMDisk.ps1'
DEBUG: Resource Reporting Phase Done.
DEBUG: Generating Quota Usage sheet for: 0 Subscriptions/Regions.
DEBUG: Looking for the following file: D:\Download\ARI-main\Extras\QuotaUsage.ps1
DEBUG: Checking if Should Generate Security Center Sheet.
DEBUG: Generating Security Center Sheet.
DEBUG: Looking for the following file: D:\Download\ARI-main\Extras\SecurityCenter.ps1
DEBUG: Checking if Should Generate Advisory Sheet.
DEBUG: Generating Advisor Sheet.
DEBUG: Looking for the following file: D:\Download\ARI-main\Extras\Advisory.ps1
DEBUG: Generating Subscription sheet for: 1 Subscriptions.
DEBUG: Looking for the following file: D:\Download\ARI-main\Extras\Subscriptions.ps1
DEBUG: Generating Overview sheet (Charts).
DEBUG: Looking for the following file: D:\Download\ARI-main\Extras\Charts.ps1
DEBUG: Finished Charts Phase.
Report Complete. Total Runtime was: ,52 Minutes
Total Resources: 27
Total Advisories: 1
Total Security Advisories: 0

**Comment by Claudio-Merola** [comment]
Hi,

There are a few scenarios that might cause this, by default the Diagram is focused on inter-connected vnets, in case where the environment is not very large it might cause that.

I suggest you edit the file "DrawIODiagram.ps1" at the line 23 and change:

From:
$Global:FullEnvironment = $false 

To:
$Global:FullEnvironment = $true

I believe that will create the diagram for the full environment.

**Comment by aloizeau** [comment]
Hi Claudio ; 
Thank for your respond, I just test it but nothing change for me, the diagram is empty after execution of the script.

- Do you have another idea ?

**Comment by aloizeau** [comment]
Does it work without vNet ?

**Comment by aloizeau** [comment]
Do you have somes new idea on this issue ?

**Comment by Claudio-Merola** [comment]
Hello,

That's very strange, how many VNETs do you have in the environment?

**Comment by aloizeau** [comment]
Hello Claudio,
My solution don't use vnet, it's only a full public PaaS solution today.
