### ISSUE TITLE
Draw.io graph is almost empty

### ISSUE THREAD

**Issue by KlemenDanfoss** [microsoft/ARI#97]
Hi,

Windows 11 Enterprise 22H2
PSVersion                      5.1.22621.963
{
  "azure-cli": "2.44.1",
  "azure-cli-core": "2.44.1",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {
    "account": "0.2.5",
    "aks-preview": "0.5.122",
    "azure-devops": "0.25.0",
    "containerapp": "0.3.20",
    "log-analytics": "0.2.2",
    "resource-graph": "2.1.0"
  }
}

I run the script like this :
.\AzureResourceInventory.ps1 -Diagram -TenantID <Tenant ID> -Subscription <SUBSCRIPTION ID>

On the diagram I get :
- 'On Premises Environment' icon
- two local network gateways

Debug mode doesn't really output anything useful.

**Comment by PeterBursky** [comment]
OK, this explains my experience - I did get most of the environment in my diagram, but a few isolated VNets were missed out. Is that something that could be added as a parameter instead of editing the PS script?

**Comment by Claudio-Merola** [comment]
For now editing the script is the only way, we might include it as a "hidden" parameter or something in the future.

I'm working in a upgrade for the script, so we might include this as well.

**Comment by Claudio-Merola** [comment]
Hello,

We added that feature in the new version 3.0, can you try that and let me know if works?

Thanks
